"""Hermaniland - Mediocampistas (Midfielders) Database"""

MIDFIELDERS = [
    {"name": "Patrick Mboma", "position": "CDM", "speed": 94, "dribbling": 92, "shooting": 76, "defense": 85, "physical": 91, "iq": 98, "team": "Inter Milan", "era": "2000s"},
    {"name": "Juan Manuel Barrios", "position": "CM", "speed": 90, "dribbling": 89, "shooting": 81, "defense": 83, "physical": 89, "iq": 96, "team": "AC Milan", "era": "1970s"},
    {"name": "Park Chu-young", "position": "CM", "speed": 93, "dribbling": 91, "shooting": 86, "defense": 83, "physical": 85, "iq": 93, "team": "Real Madrid", "era": "2010s"},
    {"name": "Miguel Ángel Herrera", "position": "CM", "speed": 94, "dribbling": 87, "shooting": 72, "defense": 75, "physical": 94, "iq": 97, "team": "Bayern Munich", "era": "2010s"},
    {"name": "Oleksandr Zinchenko", "position": "CM", "speed": 86, "dribbling": 87, "shooting": 81, "defense": 84, "physical": 75, "iq": 96, "team": "Liverpool", "era": "1990s"},
    {"name": "Nilton Santos", "position": "CDM", "speed": 82, "dribbling": 91, "shooting": 76, "defense": 82, "physical": 89, "iq": 97, "team": "Manchester United", "era": "1990s"},
    {"name": "Aymeric Laporte", "position": "CDM", "speed": 89, "dribbling": 87, "shooting": 72, "defense": 81, "physical": 87, "iq": 96, "team": "Arsenal", "era": "1990s"},
    {"name": "Ferenc Puskás", "position": "CAM", "speed": 94, "dribbling": 90, "shooting": 68, "defense": 81, "physical": 98, "iq": 92, "team": "AC Milan", "era": "2010s"},
    {"name": "Steven Gerrard", "position": "CAM", "speed": 94, "dribbling": 90, "shooting": 75, "defense": 71, "physical": 83, "iq": 95, "team": "Arsenal", "era": "1990s"},
    {"name": "Julián Araujo", "position": "CM", "speed": 87, "dribbling": 87, "shooting": 71, "defense": 79, "physical": 85, "iq": 95, "team": "Liverpool", "era": "2020s"},
    {"name": "Peter Schmeichel", "position": "CM", "speed": 84, "dribbling": 87, "shooting": 76, "defense": 76, "physical": 87, "iq": 98, "team": "Manchester United", "era": "1990s"},
    {"name": "Maracanã", "position": "CDM", "speed": 94, "dribbling": 89, "shooting": 80, "defense": 76, "physical": 98, "iq": 92, "team": "Real Madrid", "era": "1970s"},
    {"name": "Mikaël Silvestre", "position": "CM", "speed": 79, "dribbling": 84, "shooting": 87, "defense": 83, "physical": 96, "iq": 98, "team": "AC Milan", "era": "2010s"},
    {"name": "Marc Vivien Foé", "position": "CDM", "speed": 90, "dribbling": 74, "shooting": 72, "defense": 81, "physical": 76, "iq": 98, "team": "Real Madrid", "era": "1950s"},
    {"name": "Lee Young-pyo", "position": "CDM", "speed": 83, "dribbling": 88, "shooting": 81, "defense": 76, "physical": 98, "iq": 97, "team": "Arsenal", "era": "1980s"},
    {"name": "Sánchez Hugo", "position": "CDM", "speed": 82, "dribbling": 83, "shooting": 81, "defense": 82, "physical": 80, "iq": 96, "team": "Chelsea", "era": "1950s"},
    {"name": "David Beckham", "position": "CM", "speed": 84, "dribbling": 83, "shooting": 80, "defense": 85, "physical": 81, "iq": 93, "team": "Arsenal", "era": "2020s"},
    {"name": "Petr Čech", "position": "CAM", "speed": 94, "dribbling": 88, "shooting": 86, "defense": 74, "physical": 75, "iq": 91, "team": "Napoli", "era": "1930s"},
    {"name": "Mark González", "position": "CDM", "speed": 79, "dribbling": 88, "shooting": 74, "defense": 76, "physical": 80, "iq": 97, "team": "Juventus", "era": "2000s"},
    {"name": "Efraín Juárez", "position": "CAM", "speed": 80, "dribbling": 90, "shooting": 73, "defense": 83, "physical": 77, "iq": 92, "team": "Real Madrid", "era": "1930s"},
    {"name": "Neymar Santos Junior", "position": "CM", "speed": 88, "dribbling": 73, "shooting": 81, "defense": 81, "physical": 85, "iq": 97, "team": "Juventus", "era": "2010s"},
    {"name": "Mauricio Isla", "position": "CM", "speed": 83, "dribbling": 84, "shooting": 83, "defense": 75, "physical": 75, "iq": 97, "team": "Real Madrid", "era": "1980s"},
    {"name": "Alexis Mac Allister", "position": "CAM", "speed": 92, "dribbling": 77, "shooting": 88, "defense": 85, "physical": 84, "iq": 91, "team": "Inter Milan", "era": "2020s"},
    {"name": "Gonda Shuichi", "position": "CAM", "speed": 94, "dribbling": 89, "shooting": 83, "defense": 73, "physical": 82, "iq": 90, "team": "AC Milan", "era": "1980s"},
    {"name": "Paul Pogba", "position": "CM", "speed": 92, "dribbling": 78, "shooting": 85, "defense": 83, "physical": 78, "iq": 91, "team": "Bayern Munich", "era": "1930s"},
    {"name": "Raúl Jiménez", "position": "CAM", "speed": 92, "dribbling": 80, "shooting": 67, "defense": 73, "physical": 88, "iq": 95, "team": "Paris SG", "era": "1930s"},
    {"name": "Percy Olivares", "position": "CAM", "speed": 91, "dribbling": 73, "shooting": 79, "defense": 75, "physical": 82, "iq": 98, "team": "Chelsea", "era": "1980s"},
    {"name": "Morten Olsen", "position": "CM", "speed": 89, "dribbling": 82, "shooting": 77, "defense": 79, "physical": 98, "iq": 92, "team": "Manchester United", "era": "2000s"},
    {"name": "Índio", "position": "CDM", "speed": 89, "dribbling": 83, "shooting": 81, "defense": 74, "physical": 94, "iq": 94, "team": "Bayern Munich", "era": "1980s"},
    {"name": "Casemiro", "position": "CDM", "speed": 80, "dribbling": 78, "shooting": 73, "defense": 84, "physical": 83, "iq": 96, "team": "Inter Milan", "era": "1970s"},
    {"name": "Maldonado Juan", "position": "CDM", "speed": 84, "dribbling": 72, "shooting": 70, "defense": 84, "physical": 97, "iq": 97, "team": "Liverpool", "era": "2000s"},
    {"name": "Abedi Pelé", "position": "CAM", "speed": 82, "dribbling": 89, "shooting": 73, "defense": 67, "physical": 97, "iq": 98, "team": "Juventus", "era": "2000s"},
    {"name": "Ivan Toney", "position": "CM", "speed": 92, "dribbling": 85, "shooting": 66, "defense": 80, "physical": 91, "iq": 88, "team": "Inter Milan", "era": "2000s"},
    {"name": "Ítalo Espinoza", "position": "CM", "speed": 86, "dribbling": 83, "shooting": 74, "defense": 82, "physical": 85, "iq": 91, "team": "Paris SG", "era": "2020s"},
    {"name": "Pavel Nedvěd", "position": "CM", "speed": 90, "dribbling": 83, "shooting": 81, "defense": 65, "physical": 88, "iq": 97, "team": "Inter Milan", "era": "2000s"},
    {"name": "Mason Mount", "position": "CDM", "speed": 87, "dribbling": 84, "shooting": 88, "defense": 77, "physical": 84, "iq": 92, "team": "Liverpool", "era": "1930s"},
    {"name": "Roque Máspoli", "position": "CDM", "speed": 84, "dribbling": 88, "shooting": 78, "defense": 72, "physical": 85, "iq": 94, "team": "Paris SG", "era": "1980s"},
    {"name": "Neumann", "position": "CAM", "speed": 92, "dribbling": 80, "shooting": 87, "defense": 72, "physical": 89, "iq": 94, "team": "Manchester United", "era": "1990s"},
    {"name": "Figo", "position": "CM", "speed": 91, "dribbling": 87, "shooting": 83, "defense": 61, "physical": 89, "iq": 96, "team": "Napoli", "era": "2020s"},
    {"name": "Lennart Bergström", "position": "CM", "speed": 92, "dribbling": 90, "shooting": 68, "defense": 69, "physical": 79, "iq": 90, "team": "Napoli", "era": "1950s"},
    {"name": "Thiago Silva", "position": "CM", "speed": 87, "dribbling": 85, "shooting": 67, "defense": 81, "physical": 94, "iq": 89, "team": "Barcelona", "era": "2010s"},
    {"name": "Santiago Cañizares", "position": "CM", "speed": 93, "dribbling": 81, "shooting": 82, "defense": 71, "physical": 88, "iq": 93, "team": "Napoli", "era": "2020s"},
    {"name": "Ivan Hasek", "position": "CAM", "speed": 89, "dribbling": 85, "shooting": 65, "defense": 67, "physical": 87, "iq": 95, "team": "Chelsea", "era": "2010s"},
    {"name": "Gennaro Gattuso", "position": "CAM", "speed": 88, "dribbling": 81, "shooting": 67, "defense": 78, "physical": 86, "iq": 92, "team": "Real Madrid", "era": "1930s"},
    {"name": "Nicolás Domínguez", "position": "CM", "speed": 91, "dribbling": 79, "shooting": 73, "defense": 68, "physical": 83, "iq": 96, "team": "Napoli", "era": "2010s"},
    {"name": "Fred", "position": "CM", "speed": 89, "dribbling": 83, "shooting": 78, "defense": 70, "physical": 86, "iq": 94, "team": "Chelsea", "era": "1930s"},
    {"name": "Park Ji-sung", "position": "CDM", "speed": 93, "dribbling": 92, "shooting": 88, "defense": 77, "physical": 83, "iq": 84, "team": "Chelsea", "era": "1950s"},
    {"name": "Alessandro Bastoni", "position": "CDM", "speed": 94, "dribbling": 83, "shooting": 86, "defense": 69, "physical": 92, "iq": 92, "team": "Paris SG", "era": "1990s"},
    {"name": "Michael Owen", "position": "CAM", "speed": 80, "dribbling": 92, "shooting": 84, "defense": 84, "physical": 97, "iq": 87, "team": "Chelsea", "era": "1950s"},
    {"name": "Neymar Jr", "position": "CM", "speed": 78, "dribbling": 85, "shooting": 88, "defense": 72, "physical": 80, "iq": 97, "team": "Bayern Munich", "era": "1970s"},
    {"name": "Marco Tardelli", "position": "CM", "speed": 83, "dribbling": 89, "shooting": 70, "defense": 62, "physical": 89, "iq": 97, "team": "Juventus", "era": "1990s"},
    {"name": "Júnior", "position": "CM", "speed": 91, "dribbling": 88, "shooting": 76, "defense": 63, "physical": 94, "iq": 93, "team": "Manchester United", "era": "1990s"},
    {"name": "Carlos Vela", "position": "CDM", "speed": 86, "dribbling": 82, "shooting": 65, "defense": 82, "physical": 86, "iq": 89, "team": "Juventus", "era": "1980s"},
    {"name": "Simeone", "position": "CAM", "speed": 90, "dribbling": 78, "shooting": 83, "defense": 76, "physical": 85, "iq": 92, "team": "Juventus", "era": "1980s"},
    {"name": "Ribamar", "position": "CDM", "speed": 79, "dribbling": 89, "shooting": 74, "defense": 79, "physical": 78, "iq": 90, "team": "Chelsea", "era": "1970s"},
    {"name": "Ruud Krol", "position": "CDM", "speed": 89, "dribbling": 80, "shooting": 78, "defense": 68, "physical": 94, "iq": 95, "team": "Paris SG", "era": "1990s"},
    {"name": "Paulo Dybala", "position": "CM", "speed": 93, "dribbling": 75, "shooting": 73, "defense": 64, "physical": 91, "iq": 97, "team": "Barcelona", "era": "2020s"},
    {"name": "Bixente Lizarazu", "position": "CM", "speed": 87, "dribbling": 84, "shooting": 74, "defense": 81, "physical": 85, "iq": 87, "team": "Barcelona", "era": "1930s"},
    {"name": "Cabrini", "position": "CM", "speed": 94, "dribbling": 72, "shooting": 71, "defense": 78, "physical": 80, "iq": 91, "team": "Liverpool", "era": "2020s"},
    {"name": "Vertonghen", "position": "CDM", "speed": 87, "dribbling": 75, "shooting": 84, "defense": 70, "physical": 81, "iq": 97, "team": "Chelsea", "era": "1990s"},
    {"name": "Pepe", "position": "CDM", "speed": 92, "dribbling": 88, "shooting": 71, "defense": 76, "physical": 82, "iq": 85, "team": "Manchester United", "era": "1930s"},
    {"name": "Zinedine Zidane", "position": "CAM", "speed": 93, "dribbling": 91, "shooting": 68, "defense": 74, "physical": 81, "iq": 84, "team": "Real Madrid", "era": "1980s"},
    {"name": "Heintze", "position": "CAM", "speed": 78, "dribbling": 89, "shooting": 65, "defense": 83, "physical": 98, "iq": 88, "team": "Paris SG", "era": "2020s"},
    {"name": "Breitner Paul", "position": "CAM", "speed": 81, "dribbling": 78, "shooting": 83, "defense": 77, "physical": 97, "iq": 95, "team": "Inter Milan", "era": "2000s"},
    {"name": "Alphonso Davies", "position": "CM", "speed": 80, "dribbling": 79, "shooting": 78, "defense": 70, "physical": 78, "iq": 98, "team": "Manchester United", "era": "1930s"},
    {"name": "Jackson Martínez", "position": "CDM", "speed": 91, "dribbling": 75, "shooting": 74, "defense": 79, "physical": 75, "iq": 90, "team": "Manchester United", "era": "1980s"},
    {"name": "Julio Pérez", "position": "CDM", "speed": 88, "dribbling": 84, "shooting": 83, "defense": 65, "physical": 82, "iq": 94, "team": "Arsenal", "era": "2020s"},
    {"name": "Willian", "position": "CDM", "speed": 88, "dribbling": 91, "shooting": 88, "defense": 78, "physical": 94, "iq": 84, "team": "Liverpool", "era": "1970s"},
    {"name": "Capdevila", "position": "CDM", "speed": 81, "dribbling": 89, "shooting": 88, "defense": 81, "physical": 87, "iq": 87, "team": "Real Madrid", "era": "2000s"},
    {"name": "Ramiro Fonseca", "position": "CAM", "speed": 94, "dribbling": 92, "shooting": 84, "defense": 75, "physical": 98, "iq": 82, "team": "Manchester United", "era": "2000s"},
    {"name": "Daniel Bertoni", "position": "CAM", "speed": 82, "dribbling": 70, "shooting": 65, "defense": 77, "physical": 85, "iq": 98, "team": "Napoli", "era": "1950s"},
    {"name": "Péter Palotás", "position": "CAM", "speed": 89, "dribbling": 76, "shooting": 67, "defense": 64, "physical": 98, "iq": 98, "team": "Juventus", "era": "2000s"},
    {"name": "Cristiane", "position": "CAM", "speed": 89, "dribbling": 92, "shooting": 76, "defense": 84, "physical": 81, "iq": 80, "team": "Juventus", "era": "1970s"},
    {"name": "Nicolas Anelka", "position": "CDM", "speed": 87, "dribbling": 83, "shooting": 70, "defense": 68, "physical": 96, "iq": 93, "team": "Napoli", "era": "1980s"},
    {"name": "Carlos Valderrama", "position": "CDM", "speed": 86, "dribbling": 76, "shooting": 70, "defense": 68, "physical": 80, "iq": 97, "team": "Liverpool", "era": "1980s"},
    {"name": "Mats Hummels", "position": "CM", "speed": 94, "dribbling": 70, "shooting": 77, "defense": 71, "physical": 77, "iq": 94, "team": "Napoli", "era": "1930s"},
    {"name": "David Alaba", "position": "CDM", "speed": 81, "dribbling": 85, "shooting": 75, "defense": 65, "physical": 96, "iq": 96, "team": "Barcelona", "era": "1980s"},
    {"name": "Heinze Gabriel", "position": "CAM", "speed": 94, "dribbling": 71, "shooting": 74, "defense": 79, "physical": 95, "iq": 89, "team": "Manchester United", "era": "2010s"},
    {"name": "Guido Rodríguez", "position": "CAM", "speed": 84, "dribbling": 77, "shooting": 82, "defense": 79, "physical": 97, "iq": 91, "team": "Chelsea", "era": "1980s"},
    {"name": "Alexis Sánchez", "position": "CAM", "speed": 84, "dribbling": 91, "shooting": 69, "defense": 69, "physical": 83, "iq": 89, "team": "Napoli", "era": "1950s"},
    {"name": "Sergio Busquets", "position": "CAM", "speed": 79, "dribbling": 91, "shooting": 66, "defense": 76, "physical": 78, "iq": 88, "team": "Real Madrid", "era": "1970s"},
    {"name": "Dani Alves", "position": "CAM", "speed": 84, "dribbling": 87, "shooting": 74, "defense": 77, "physical": 84, "iq": 87, "team": "Manchester United", "era": "1990s"},
    {"name": "Obdulio Varela", "position": "CAM", "speed": 88, "dribbling": 88, "shooting": 82, "defense": 80, "physical": 91, "iq": 83, "team": "Juventus", "era": "1980s"},
    {"name": "Murillo Cearense", "position": "CM", "speed": 85, "dribbling": 92, "shooting": 77, "defense": 84, "physical": 97, "iq": 80, "team": "Juventus", "era": "1970s"},
    {"name": "Ahn Jung-hwan", "position": "CM", "speed": 94, "dribbling": 84, "shooting": 86, "defense": 83, "physical": 90, "iq": 80, "team": "Manchester United", "era": "1950s"},
    {"name": "Presnel Kimpembe", "position": "CDM", "speed": 78, "dribbling": 77, "shooting": 73, "defense": 84, "physical": 80, "iq": 91, "team": "Bayern Munich", "era": "1930s"},
    {"name": "Roy Keane", "position": "CAM", "speed": 86, "dribbling": 90, "shooting": 88, "defense": 69, "physical": 98, "iq": 88, "team": "Barcelona", "era": "2020s"},
    {"name": "Roque Santa Cruz", "position": "CAM", "speed": 79, "dribbling": 71, "shooting": 85, "defense": 75, "physical": 89, "iq": 98, "team": "Bayern Munich", "era": "1950s"},
    {"name": "Igor Lichnovsky", "position": "CM", "speed": 92, "dribbling": 72, "shooting": 72, "defense": 60, "physical": 92, "iq": 98, "team": "Inter Milan", "era": "2010s"},
    {"name": "Naohiro Takahara", "position": "CM", "speed": 81, "dribbling": 92, "shooting": 70, "defense": 75, "physical": 88, "iq": 86, "team": "Bayern Munich", "era": "1980s"},
    {"name": "Sergio Ramos", "position": "CDM", "speed": 86, "dribbling": 87, "shooting": 80, "defense": 79, "physical": 88, "iq": 84, "team": "Manchester United", "era": "1970s"},
    {"name": "Formiga", "position": "CDM", "speed": 80, "dribbling": 70, "shooting": 68, "defense": 82, "physical": 90, "iq": 94, "team": "Real Madrid", "era": "1990s"},
    {"name": "Daniel Passarella", "position": "CAM", "speed": 84, "dribbling": 77, "shooting": 85, "defense": 69, "physical": 85, "iq": 95, "team": "Liverpool", "era": "1990s"},
    {"name": "Johan Cruyff", "position": "CAM", "speed": 83, "dribbling": 92, "shooting": 79, "defense": 79, "physical": 83, "iq": 83, "team": "Manchester United", "era": "2020s"},
    {"name": "Lajos Czedroni", "position": "CAM", "speed": 93, "dribbling": 81, "shooting": 67, "defense": 64, "physical": 89, "iq": 91, "team": "Bayern Munich", "era": "2000s"},
    {"name": "Gyula Feldmann", "position": "CM", "speed": 78, "dribbling": 74, "shooting": 75, "defense": 75, "physical": 78, "iq": 96, "team": "Real Madrid", "era": "1980s"},
    {"name": "Carlos Alberto Pérez", "position": "CM", "speed": 82, "dribbling": 75, "shooting": 74, "defense": 66, "physical": 76, "iq": 98, "team": "Barcelona", "era": "1970s"},
    {"name": "Marco Materazzi", "position": "CAM", "speed": 90, "dribbling": 91, "shooting": 70, "defense": 70, "physical": 89, "iq": 84, "team": "Real Madrid", "era": "1930s"},
    {"name": "Maicon", "position": "CAM", "speed": 88, "dribbling": 81, "shooting": 87, "defense": 70, "physical": 96, "iq": 90, "team": "Real Madrid", "era": "1990s"},
    {"name": "Sendoya Carlos", "position": "CAM", "speed": 79, "dribbling": 82, "shooting": 85, "defense": 74, "physical": 79, "iq": 92, "team": "Barcelona", "era": "1930s"},
    {"name": "Victor Moses", "position": "CM", "speed": 85, "dribbling": 91, "shooting": 84, "defense": 70, "physical": 84, "iq": 86, "team": "Barcelona", "era": "1970s"},
    {"name": "Moise Kean", "position": "CM", "speed": 94, "dribbling": 92, "shooting": 77, "defense": 74, "physical": 82, "iq": 79, "team": "Barcelona", "era": "1970s"},
    {"name": "Matteo Guendouzi", "position": "CDM", "speed": 82, "dribbling": 71, "shooting": 69, "defense": 71, "physical": 84, "iq": 97, "team": "Napoli", "era": "1970s"},
    {"name": "Obi Mikel", "position": "CM", "speed": 86, "dribbling": 71, "shooting": 80, "defense": 78, "physical": 82, "iq": 91, "team": "Bayern Munich", "era": "2010s"},
    {"name": "Dayot Upamecano", "position": "CM", "speed": 81, "dribbling": 91, "shooting": 67, "defense": 82, "physical": 75, "iq": 81, "team": "Juventus", "era": "1990s"},
    {"name": "Beltrán", "position": "CM", "speed": 85, "dribbling": 78, "shooting": 68, "defense": 85, "physical": 97, "iq": 84, "team": "Real Madrid", "era": "2000s"},
    {"name": "Christian Benavente", "position": "CDM", "speed": 88, "dribbling": 90, "shooting": 84, "defense": 72, "physical": 92, "iq": 83, "team": "Liverpool", "era": "1950s"},
    {"name": "Trent Alexander-Arnold", "position": "CDM", "speed": 82, "dribbling": 74, "shooting": 85, "defense": 80, "physical": 96, "iq": 90, "team": "Inter Milan", "era": "1950s"},
    {"name": "Samuel Eto'o", "position": "CDM", "speed": 88, "dribbling": 90, "shooting": 69, "defense": 64, "physical": 86, "iq": 87, "team": "Napoli", "era": "1980s"},
    {"name": "Chuleta", "position": "CAM", "speed": 87, "dribbling": 81, "shooting": 81, "defense": 78, "physical": 92, "iq": 85, "team": "Bayern Munich", "era": "2000s"},
    {"name": "Pérez Arce", "position": "CAM", "speed": 82, "dribbling": 92, "shooting": 68, "defense": 62, "physical": 96, "iq": 90, "team": "Barcelona", "era": "1980s"},
    {"name": "N'Golo Kanté", "position": "CM", "speed": 93, "dribbling": 85, "shooting": 88, "defense": 61, "physical": 89, "iq": 88, "team": "AC Milan", "era": "1950s"},
    {"name": "Sergei Ignashevich", "position": "CM", "speed": 93, "dribbling": 79, "shooting": 73, "defense": 71, "physical": 96, "iq": 86, "team": "Chelsea", "era": "1950s"},
    {"name": "Kai Havertz", "position": "CM", "speed": 78, "dribbling": 89, "shooting": 70, "defense": 60, "physical": 86, "iq": 94, "team": "Napoli", "era": "1950s"},
    {"name": "José Pepe Maspoli", "position": "CDM", "speed": 86, "dribbling": 73, "shooting": 71, "defense": 60, "physical": 87, "iq": 98, "team": "AC Milan", "era": "1930s"},
    {"name": "Sérgio Manoel", "position": "CM", "speed": 86, "dribbling": 87, "shooting": 65, "defense": 77, "physical": 90, "iq": 82, "team": "Barcelona", "era": "1930s"},
    {"name": "Oscar", "position": "CM", "speed": 89, "dribbling": 78, "shooting": 65, "defense": 79, "physical": 90, "iq": 84, "team": "Chelsea", "era": "1970s"},
    {"name": "Otávio", "position": "CDM", "speed": 91, "dribbling": 79, "shooting": 83, "defense": 66, "physical": 75, "iq": 89, "team": "Napoli", "era": "1950s"},
    {"name": "Andrey Arshavin", "position": "CDM", "speed": 87, "dribbling": 84, "shooting": 69, "defense": 65, "physical": 94, "iq": 89, "team": "Real Madrid", "era": "1950s"},
    {"name": "Rodrygo", "position": "CAM", "speed": 92, "dribbling": 92, "shooting": 67, "defense": 66, "physical": 82, "iq": 82, "team": "Barcelona", "era": "2010s"},
    {"name": "Wim Kieft", "position": "CAM", "speed": 84, "dribbling": 90, "shooting": 69, "defense": 74, "physical": 98, "iq": 83, "team": "Chelsea", "era": "1980s"},
    {"name": "Blaise Matuidi", "position": "CAM", "speed": 79, "dribbling": 91, "shooting": 65, "defense": 74, "physical": 98, "iq": 85, "team": "Bayern Munich", "era": "1970s"},
    {"name": "Scacchetti", "position": "CM", "speed": 85, "dribbling": 70, "shooting": 73, "defense": 82, "physical": 81, "iq": 88, "team": "Liverpool", "era": "2000s"},
    {"name": "Zbigniew Boniek", "position": "CDM", "speed": 83, "dribbling": 70, "shooting": 79, "defense": 72, "physical": 77, "iq": 94, "team": "Chelsea", "era": "1930s"},
    {"name": "Denílson", "position": "CDM", "speed": 84, "dribbling": 78, "shooting": 87, "defense": 77, "physical": 85, "iq": 87, "team": "Real Madrid", "era": "2000s"},
    {"name": "Gianluca Zambrotta", "position": "CAM", "speed": 81, "dribbling": 87, "shooting": 73, "defense": 61, "physical": 86, "iq": 92, "team": "Napoli", "era": "1980s"},
    {"name": "Ramires", "position": "CM", "speed": 92, "dribbling": 77, "shooting": 66, "defense": 63, "physical": 85, "iq": 90, "team": "Liverpool", "era": "1980s"},
    {"name": "Jay-Jay Okocha", "position": "CM", "speed": 86, "dribbling": 83, "shooting": 69, "defense": 85, "physical": 77, "iq": 79, "team": "Bayern Munich", "era": "2020s"},
    {"name": "Facundo Medina", "position": "CDM", "speed": 94, "dribbling": 85, "shooting": 73, "defense": 75, "physical": 80, "iq": 79, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Rúben Neves", "position": "CDM", "speed": 80, "dribbling": 71, "shooting": 85, "defense": 81, "physical": 77, "iq": 90, "team": "Napoli", "era": "1930s"},
    {"name": "Giampiero Boniperti", "position": "CDM", "speed": 88, "dribbling": 77, "shooting": 81, "defense": 79, "physical": 92, "iq": 84, "team": "AC Milan", "era": "1980s"},
    {"name": "Móric", "position": "CAM", "speed": 94, "dribbling": 75, "shooting": 78, "defense": 61, "physical": 96, "iq": 91, "team": "Chelsea", "era": "1990s"},
    {"name": "Shinji Ono", "position": "CAM", "speed": 87, "dribbling": 79, "shooting": 70, "defense": 64, "physical": 91, "iq": 91, "team": "Arsenal", "era": "2000s"},
    {"name": "Emilio Butragueño", "position": "CAM", "speed": 91, "dribbling": 91, "shooting": 73, "defense": 60, "physical": 96, "iq": 85, "team": "Chelsea", "era": "1990s"},
    {"name": "Veludo", "position": "CAM", "speed": 81, "dribbling": 88, "shooting": 67, "defense": 83, "physical": 92, "iq": 80, "team": "Manchester United", "era": "1980s"},
    {"name": "Conceição", "position": "CM", "speed": 80, "dribbling": 82, "shooting": 72, "defense": 61, "physical": 97, "iq": 94, "team": "Manchester United", "era": "2000s"},
    {"name": "Diego Maradona", "position": "CM", "speed": 87, "dribbling": 77, "shooting": 66, "defense": 61, "physical": 94, "iq": 93, "team": "Bayern Munich", "era": "1980s"},
    {"name": "Philipp Lahm", "position": "CM", "speed": 94, "dribbling": 81, "shooting": 81, "defense": 60, "physical": 94, "iq": 88, "team": "AC Milan", "era": "2020s"},
    {"name": "Joszef Háda", "position": "CDM", "speed": 89, "dribbling": 84, "shooting": 78, "defense": 66, "physical": 88, "iq": 86, "team": "Chelsea", "era": "1990s"},
    {"name": "Timoteo Martínez", "position": "CDM", "speed": 85, "dribbling": 87, "shooting": 65, "defense": 69, "physical": 81, "iq": 85, "team": "AC Milan", "era": "2000s"},
    {"name": "Bielsa Marcelo", "position": "CAM", "speed": 79, "dribbling": 92, "shooting": 82, "defense": 80, "physical": 86, "iq": 80, "team": "Arsenal", "era": "1950s"},
    {"name": "Thierry Henry", "position": "CAM", "speed": 79, "dribbling": 74, "shooting": 77, "defense": 76, "physical": 94, "iq": 91, "team": "Paris SG", "era": "2020s"},
    {"name": "Harry Maguire", "position": "CAM", "speed": 91, "dribbling": 83, "shooting": 67, "defense": 73, "physical": 88, "iq": 82, "team": "Napoli", "era": "1970s"},
    {"name": "Elías Figueroa", "position": "CM", "speed": 84, "dribbling": 75, "shooting": 82, "defense": 61, "physical": 86, "iq": 95, "team": "Napoli", "era": "2020s"},
    {"name": "Salvador Cabañas", "position": "CM", "speed": 94, "dribbling": 71, "shooting": 72, "defense": 79, "physical": 83, "iq": 83, "team": "Inter Milan", "era": "2020s"},
    {"name": "Roberto Chale", "position": "CDM", "speed": 78, "dribbling": 80, "shooting": 72, "defense": 64, "physical": 87, "iq": 94, "team": "AC Milan", "era": "2020s"},
    {"name": "Defelice", "position": "CDM", "speed": 78, "dribbling": 88, "shooting": 83, "defense": 66, "physical": 86, "iq": 89, "team": "Manchester United", "era": "1970s"},
    {"name": "Robert Lewandowski", "position": "CDM", "speed": 89, "dribbling": 75, "shooting": 83, "defense": 80, "physical": 86, "iq": 83, "team": "Liverpool", "era": "1990s"},
    {"name": "Giuseppe Meazza", "position": "CDM", "speed": 84, "dribbling": 86, "shooting": 82, "defense": 70, "physical": 97, "iq": 85, "team": "Inter Milan", "era": "2020s"},
    {"name": "Corbatta Julio", "position": "CAM", "speed": 94, "dribbling": 75, "shooting": 76, "defense": 75, "physical": 84, "iq": 83, "team": "Napoli", "era": "1980s"},
    {"name": "Kingsley Coman", "position": "CAM", "speed": 85, "dribbling": 81, "shooting": 79, "defense": 72, "physical": 92, "iq": 86, "team": "Manchester United", "era": "1950s"},
    {"name": "Alejandro Garnacho", "position": "CAM", "speed": 86, "dribbling": 70, "shooting": 82, "defense": 62, "physical": 77, "iq": 96, "team": "Inter Milan", "era": "1990s"},
    {"name": "Emerson", "position": "CAM", "speed": 87, "dribbling": 84, "shooting": 66, "defense": 73, "physical": 85, "iq": 83, "team": "Manchester United", "era": "2000s"},
    {"name": "Eusébio", "position": "CAM", "speed": 80, "dribbling": 76, "shooting": 87, "defense": 76, "physical": 78, "iq": 89, "team": "Juventus", "era": "1950s"},
    {"name": "Gérson", "position": "CM", "speed": 86, "dribbling": 88, "shooting": 78, "defense": 65, "physical": 91, "iq": 85, "team": "Napoli", "era": "2000s"},
    {"name": "Jan Tomaszewski", "position": "CM", "speed": 82, "dribbling": 86, "shooting": 79, "defense": 73, "physical": 81, "iq": 84, "team": "Napoli", "era": "2010s"},
    {"name": "Luis Arconada", "position": "CDM", "speed": 92, "dribbling": 83, "shooting": 73, "defense": 74, "physical": 98, "iq": 80, "team": "Real Madrid", "era": "1970s"},
    {"name": "Roman Shirokov", "position": "CDM", "speed": 78, "dribbling": 80, "shooting": 77, "defense": 67, "physical": 98, "iq": 92, "team": "Bayern Munich", "era": "1950s"},
    {"name": "Michael Laudrup", "position": "CDM", "speed": 92, "dribbling": 76, "shooting": 74, "defense": 77, "physical": 86, "iq": 82, "team": "Real Madrid", "era": "1950s"},
    {"name": "Sergio Batista", "position": "CDM", "speed": 88, "dribbling": 81, "shooting": 67, "defense": 62, "physical": 86, "iq": 89, "team": "Paris SG", "era": "2000s"},
    {"name": "Fernando Torres", "position": "CAM", "speed": 82, "dribbling": 89, "shooting": 78, "defense": 64, "physical": 96, "iq": 87, "team": "Liverpool", "era": "2010s"},
    {"name": "Mikel San José", "position": "CAM", "speed": 85, "dribbling": 76, "shooting": 77, "defense": 68, "physical": 87, "iq": 90, "team": "Chelsea", "era": "2010s"},
    {"name": "Thomas Søren", "position": "CM", "speed": 81, "dribbling": 73, "shooting": 75, "defense": 65, "physical": 91, "iq": 94, "team": "AC Milan", "era": "2000s"},
    {"name": "Mata", "position": "CDM", "speed": 79, "dribbling": 89, "shooting": 81, "defense": 79, "physical": 93, "iq": 80, "team": "Barcelona", "era": "1980s"},
    {"name": "Ronaldinho Gaúcho", "position": "CAM", "speed": 85, "dribbling": 86, "shooting": 65, "defense": 62, "physical": 90, "iq": 87, "team": "Barcelona", "era": "1970s"},
    {"name": "Douglas Costa", "position": "CM", "speed": 92, "dribbling": 77, "shooting": 69, "defense": 65, "physical": 92, "iq": 86, "team": "Arsenal", "era": "1930s"},
    {"name": "Teófilo Cubillas", "position": "CM", "speed": 89, "dribbling": 79, "shooting": 78, "defense": 70, "physical": 85, "iq": 84, "team": "Juventus", "era": "2010s"},
    {"name": "Juan Riquelme", "position": "CDM", "speed": 87, "dribbling": 87, "shooting": 77, "defense": 64, "physical": 77, "iq": 84, "team": "Real Madrid", "era": "1980s"},
    {"name": "Gerardo Torrado", "position": "CAM", "speed": 82, "dribbling": 79, "shooting": 69, "defense": 67, "physical": 82, "iq": 89, "team": "Barcelona", "era": "1950s"},
    {"name": "Silvio Piola", "position": "CAM", "speed": 94, "dribbling": 80, "shooting": 69, "defense": 64, "physical": 98, "iq": 84, "team": "AC Milan", "era": "1990s"},
    {"name": "José Luis Islas", "position": "CM", "speed": 86, "dribbling": 80, "shooting": 69, "defense": 71, "physical": 98, "iq": 84, "team": "Manchester United", "era": "1980s"},
    {"name": "Rafinha", "position": "CDM", "speed": 83, "dribbling": 74, "shooting": 72, "defense": 72, "physical": 96, "iq": 88, "team": "Real Madrid", "era": "1930s"},
    {"name": "Nicolo Barella", "position": "CDM", "speed": 91, "dribbling": 70, "shooting": 78, "defense": 66, "physical": 89, "iq": 89, "team": "Paris SG", "era": "1970s"},
    {"name": "James Maddison", "position": "CDM", "speed": 80, "dribbling": 87, "shooting": 74, "defense": 72, "physical": 82, "iq": 83, "team": "Chelsea", "era": "1930s"},
    {"name": "Fabio Cannavaro", "position": "CAM", "speed": 87, "dribbling": 81, "shooting": 76, "defense": 65, "physical": 77, "iq": 86, "team": "Bayern Munich", "era": "2020s"},
    {"name": "Kleberson", "position": "CAM", "speed": 93, "dribbling": 84, "shooting": 79, "defense": 60, "physical": 78, "iq": 84, "team": "Manchester United", "era": "1980s"},
    {"name": "Ibrahimović", "position": "CAM", "speed": 83, "dribbling": 73, "shooting": 68, "defense": 77, "physical": 78, "iq": 86, "team": "Barcelona", "era": "1990s"},
    {"name": "Carlos Tévez", "position": "CM", "speed": 83, "dribbling": 81, "shooting": 67, "defense": 70, "physical": 93, "iq": 85, "team": "Manchester United", "era": "1950s"},
    {"name": "Renato Sanches", "position": "CM", "speed": 82, "dribbling": 77, "shooting": 73, "defense": 73, "physical": 96, "iq": 86, "team": "Paris SG", "era": "1990s"},
    {"name": "Kåre Ingebrigsten", "position": "CM", "speed": 86, "dribbling": 72, "shooting": 70, "defense": 81, "physical": 87, "iq": 82, "team": "Inter Milan", "era": "1990s"},
    {"name": "William Gallas", "position": "CDM", "speed": 89, "dribbling": 70, "shooting": 74, "defense": 78, "physical": 93, "iq": 83, "team": "Liverpool", "era": "1950s"},
    {"name": "Davide Calabria", "position": "CDM", "speed": 89, "dribbling": 77, "shooting": 86, "defense": 71, "physical": 84, "iq": 83, "team": "Barcelona", "era": "2020s"},
    {"name": "Gentile", "position": "CDM", "speed": 81, "dribbling": 89, "shooting": 67, "defense": 63, "physical": 78, "iq": 85, "team": "Juventus", "era": "1930s"},
    {"name": "Ashley Cole", "position": "CAM", "speed": 80, "dribbling": 86, "shooting": 84, "defense": 81, "physical": 88, "iq": 78, "team": "Napoli", "era": "1980s"},
    {"name": "Schrijvers", "position": "CAM", "speed": 83, "dribbling": 85, "shooting": 65, "defense": 69, "physical": 82, "iq": 83, "team": "Napoli", "era": "1930s"},
    {"name": "Antonio Cabrini", "position": "CM", "speed": 92, "dribbling": 81, "shooting": 83, "defense": 63, "physical": 80, "iq": 83, "team": "Chelsea", "era": "1930s"},
    {"name": "Marta", "position": "CM", "speed": 78, "dribbling": 77, "shooting": 88, "defense": 73, "physical": 85, "iq": 87, "team": "Manchester United", "era": "1980s"},
    {"name": "Zoltan Czibor", "position": "CDM", "speed": 88, "dribbling": 72, "shooting": 69, "defense": 78, "physical": 91, "iq": 82, "team": "Real Madrid", "era": "1930s"},
    {"name": "Gilberto Silva", "position": "CDM", "speed": 83, "dribbling": 87, "shooting": 67, "defense": 72, "physical": 89, "iq": 80, "team": "Inter Milan", "era": "1980s"},
    {"name": "Yepes", "position": "CDM", "speed": 91, "dribbling": 70, "shooting": 74, "defense": 67, "physical": 84, "iq": 87, "team": "Real Madrid", "era": "2010s"},
    {"name": "Frank Leboeuf", "position": "CAM", "speed": 86, "dribbling": 71, "shooting": 82, "defense": 65, "physical": 98, "iq": 90, "team": "Paris SG", "era": "1930s"},
    {"name": "Mattia De Sciglio", "position": "CAM", "speed": 86, "dribbling": 73, "shooting": 77, "defense": 81, "physical": 91, "iq": 81, "team": "Manchester United", "era": "1980s"},
    {"name": "Ruud Gullit", "position": "CM", "speed": 83, "dribbling": 82, "shooting": 72, "defense": 76, "physical": 89, "iq": 80, "team": "Bayern Munich", "era": "2010s"},
    {"name": "Wilfred Ndidi", "position": "CM", "speed": 88, "dribbling": 87, "shooting": 87, "defense": 68, "physical": 84, "iq": 79, "team": "Real Madrid", "era": "2020s"},
    {"name": "Antonio Valencia", "position": "CM", "speed": 81, "dribbling": 85, "shooting": 68, "defense": 75, "physical": 98, "iq": 80, "team": "Bayern Munich", "era": "1980s"},
    {"name": "Mosquera", "position": "CDM", "speed": 78, "dribbling": 80, "shooting": 76, "defense": 79, "physical": 78, "iq": 82, "team": "Juventus", "era": "2000s"},
    {"name": "Tomáš Rosický", "position": "CDM", "speed": 80, "dribbling": 89, "shooting": 74, "defense": 70, "physical": 86, "iq": 81, "team": "Liverpool", "era": "2000s"},
    {"name": "Teddy Sheringham", "position": "CAM", "speed": 82, "dribbling": 82, "shooting": 75, "defense": 65, "physical": 82, "iq": 86, "team": "Inter Milan", "era": "1970s"},
    {"name": "Alexis Martín Arias", "position": "CAM", "speed": 83, "dribbling": 84, "shooting": 78, "defense": 76, "physical": 96, "iq": 79, "team": "Juventus", "era": "1980s"},
    {"name": "Ghiggia", "position": "CAM", "speed": 87, "dribbling": 82, "shooting": 79, "defense": 74, "physical": 87, "iq": 79, "team": "Manchester United", "era": "1950s"},
    {"name": "David Silva", "position": "CM", "speed": 88, "dribbling": 88, "shooting": 88, "defense": 68, "physical": 87, "iq": 78, "team": "AC Milan", "era": "2010s"},
    {"name": "David Luiz", "position": "CDM", "speed": 82, "dribbling": 72, "shooting": 80, "defense": 66, "physical": 80, "iq": 90, "team": "Bayern Munich", "era": "1980s"},
    {"name": "John Terry", "position": "CDM", "speed": 80, "dribbling": 78, "shooting": 82, "defense": 80, "physical": 88, "iq": 81, "team": "Paris SG", "era": "1990s"},
    {"name": "Garrincha", "position": "CAM", "speed": 83, "dribbling": 81, "shooting": 66, "defense": 68, "physical": 93, "iq": 84, "team": "Inter Milan", "era": "1950s"},
    {"name": "Berti Vogts", "position": "CAM", "speed": 90, "dribbling": 73, "shooting": 84, "defense": 79, "physical": 92, "iq": 79, "team": "Inter Milan", "era": "1950s"},
    {"name": "Aleksandar Kolarov", "position": "CAM", "speed": 89, "dribbling": 90, "shooting": 87, "defense": 63, "physical": 82, "iq": 79, "team": "Juventus", "era": "1990s"},
    {"name": "Ayala Marcos", "position": "CM", "speed": 84, "dribbling": 71, "shooting": 85, "defense": 60, "physical": 89, "iq": 92, "team": "Paris SG", "era": "2020s"},
    {"name": "Hallvar Thoresen", "position": "CM", "speed": 84, "dribbling": 70, "shooting": 83, "defense": 81, "physical": 86, "iq": 82, "team": "Paris SG", "era": "1970s"},
    {"name": "Darío Conca", "position": "CM", "speed": 90, "dribbling": 78, "shooting": 65, "defense": 61, "physical": 88, "iq": 85, "team": "Paris SG", "era": "1930s"},
    {"name": "Moises Caicedo", "position": "CM", "speed": 92, "dribbling": 75, "shooting": 70, "defense": 60, "physical": 88, "iq": 86, "team": "Real Madrid", "era": "2000s"},
    {"name": "Ángelo Sagal", "position": "CM", "speed": 89, "dribbling": 73, "shooting": 87, "defense": 69, "physical": 98, "iq": 84, "team": "Arsenal", "era": "1950s"},
    {"name": "Coutinho", "position": "CM", "speed": 88, "dribbling": 87, "shooting": 83, "defense": 65, "physical": 94, "iq": 79, "team": "Napoli", "era": "2010s"},
    {"name": "Mark Hughes", "position": "CAM", "speed": 81, "dribbling": 89, "shooting": 85, "defense": 62, "physical": 91, "iq": 83, "team": "Arsenal", "era": "1970s"},
    {"name": "Söyüncü", "position": "CM", "speed": 89, "dribbling": 72, "shooting": 67, "defense": 66, "physical": 89, "iq": 85, "team": "Napoli", "era": "2000s"},
    {"name": "Roger Milla", "position": "CM", "speed": 78, "dribbling": 80, "shooting": 70, "defense": 80, "physical": 77, "iq": 79, "team": "AC Milan", "era": "1980s"},
    {"name": "Julio Falcioni", "position": "CM", "speed": 82, "dribbling": 90, "shooting": 74, "defense": 64, "physical": 82, "iq": 80, "team": "Manchester United", "era": "1930s"},
    {"name": "Rigobert Song", "position": "CDM", "speed": 92, "dribbling": 87, "shooting": 73, "defense": 61, "physical": 80, "iq": 78, "team": "Liverpool", "era": "1980s"},
    {"name": "André Zambo Anguissa", "position": "CDM", "speed": 79, "dribbling": 70, "shooting": 83, "defense": 77, "physical": 98, "iq": 85, "team": "AC Milan", "era": "2000s"},
    {"name": "Vincent Aboubakar", "position": "CM", "speed": 78, "dribbling": 76, "shooting": 73, "defense": 63, "physical": 92, "iq": 89, "team": "AC Milan", "era": "2010s"},
    {"name": "Héctor Chumpitaz", "position": "CM", "speed": 85, "dribbling": 73, "shooting": 80, "defense": 69, "physical": 77, "iq": 84, "team": "Manchester United", "era": "2000s"},
    {"name": "Ramos", "position": "CDM", "speed": 92, "dribbling": 72, "shooting": 79, "defense": 65, "physical": 98, "iq": 83, "team": "Liverpool", "era": "1950s"},
    {"name": "Asprilla", "position": "CDM", "speed": 84, "dribbling": 83, "shooting": 82, "defense": 70, "physical": 97, "iq": 79, "team": "Bayern Munich", "era": "1950s"},
    {"name": "George Best", "position": "CDM", "speed": 79, "dribbling": 83, "shooting": 86, "defense": 67, "physical": 80, "iq": 83, "team": "Inter Milan", "era": "2010s"},
    {"name": "Erik Nevland", "position": "CM", "speed": 92, "dribbling": 82, "shooting": 72, "defense": 64, "physical": 95, "iq": 78, "team": "Chelsea", "era": "2010s"},
    {"name": "Leonardo Bonucci", "position": "CDM", "speed": 92, "dribbling": 73, "shooting": 73, "defense": 71, "physical": 78, "iq": 79, "team": "Juventus", "era": "1990s"},
    {"name": "Adolphe Amaéba", "position": "CAM", "speed": 85, "dribbling": 73, "shooting": 86, "defense": 62, "physical": 92, "iq": 87, "team": "Real Madrid", "era": "1980s"},
    {"name": "Gilberto Silva Jr", "position": "CAM", "speed": 83, "dribbling": 82, "shooting": 83, "defense": 65, "physical": 75, "iq": 82, "team": "Juventus", "era": "2000s"},
    {"name": "Didi", "position": "CDM", "speed": 79, "dribbling": 82, "shooting": 82, "defense": 74, "physical": 89, "iq": 79, "team": "Inter Milan", "era": "2020s"},
    {"name": "Scirea", "position": "CDM", "speed": 90, "dribbling": 79, "shooting": 68, "defense": 62, "physical": 97, "iq": 81, "team": "Chelsea", "era": "1930s"},
    {"name": "Shunsuke Nakamura", "position": "CAM", "speed": 79, "dribbling": 79, "shooting": 72, "defense": 75, "physical": 84, "iq": 80, "team": "Manchester United", "era": "1970s"},
    {"name": "Aimar", "position": "CAM", "speed": 78, "dribbling": 85, "shooting": 81, "defense": 62, "physical": 76, "iq": 84, "team": "Bayern Munich", "era": "2010s"},
    {"name": "Lilian Thuram", "position": "CDM", "speed": 85, "dribbling": 76, "shooting": 86, "defense": 73, "physical": 83, "iq": 79, "team": "AC Milan", "era": "1970s"},
    {"name": "Trincão", "position": "CDM", "speed": 91, "dribbling": 72, "shooting": 77, "defense": 60, "physical": 87, "iq": 84, "team": "Chelsea", "era": "1930s"},
    {"name": "Vavá", "position": "CDM", "speed": 91, "dribbling": 73, "shooting": 70, "defense": 71, "physical": 96, "iq": 78, "team": "Napoli", "era": "2010s"},
    {"name": "Mario Kempes", "position": "CAM", "speed": 83, "dribbling": 89, "shooting": 69, "defense": 61, "physical": 75, "iq": 79, "team": "Juventus", "era": "2020s"},
    {"name": "Toni Kroos", "position": "CAM", "speed": 82, "dribbling": 79, "shooting": 83, "defense": 72, "physical": 93, "iq": 79, "team": "Paris SG", "era": "1930s"},
    {"name": "Bastian Schweinsteiger", "position": "CAM", "speed": 84, "dribbling": 87, "shooting": 80, "defense": 63, "physical": 93, "iq": 78, "team": "Liverpool", "era": "1930s"},
    {"name": "Carles Puyol", "position": "CDM", "speed": 79, "dribbling": 70, "shooting": 67, "defense": 82, "physical": 83, "iq": 79, "team": "Real Madrid", "era": "1970s"},
    {"name": "Koeman Ronald", "position": "CDM", "speed": 84, "dribbling": 77, "shooting": 70, "defense": 66, "physical": 87, "iq": 80, "team": "Chelsea", "era": "2020s"},
    {"name": "Javier Mascherano", "position": "CM", "speed": 82, "dribbling": 87, "shooting": 72, "defense": 61, "physical": 77, "iq": 78, "team": "Barcelona", "era": "1980s"},
    {"name": "Bruno Guimaraes", "position": "CDM", "speed": 91, "dribbling": 70, "shooting": 87, "defense": 63, "physical": 95, "iq": 81, "team": "Inter Milan", "era": "1970s"},
    {"name": "Allan Simonsen", "position": "CM", "speed": 86, "dribbling": 73, "shooting": 69, "defense": 70, "physical": 92, "iq": 78, "team": "Liverpool", "era": "1980s"},
    {"name": "Michel Platini", "position": "CAM", "speed": 78, "dribbling": 76, "shooting": 86, "defense": 66, "physical": 77, "iq": 82, "team": "Bayern Munich", "era": "2010s"},
    {"name": "Claudio Bravo", "position": "CAM", "speed": 81, "dribbling": 76, "shooting": 74, "defense": 66, "physical": 97, "iq": 80, "team": "Barcelona", "era": "1980s"},
    {"name": "Carlos Butragueño", "position": "CAM", "speed": 80, "dribbling": 78, "shooting": 69, "defense": 65, "physical": 93, "iq": 80, "team": "Juventus", "era": "1930s"},
    {"name": "Luca Toni", "position": "CAM", "speed": 84, "dribbling": 71, "shooting": 65, "defense": 62, "physical": 96, "iq": 82, "team": "Arsenal", "era": "2020s"},
    {"name": "Francesco Totti", "position": "CAM", "speed": 85, "dribbling": 71, "shooting": 77, "defense": 60, "physical": 81, "iq": 82, "team": "AC Milan", "era": "2020s"},
    {"name": "Blas Riveros", "position": "CDM", "speed": 84, "dribbling": 73, "shooting": 84, "defense": 61, "physical": 93, "iq": 80, "team": "Juventus", "era": "1990s"},
]

def get_midfielders():
    """Return all midfielders"""
    return MIDFIELDERS
