"""Hermaniland - Defensas (Defenders) Database"""

DEFENDERS = [
    {"name": "Amaral", "position": "LB", "speed": 89, "dribbling": 65, "shooting": 45, "defense": 98, "physical": 94, "iq": 95, "team": "Barcelona", "era": "1950s"},
    {"name": "Álvaro Arbeloa", "position": "CB", "speed": 89, "dribbling": 65, "shooting": 57, "defense": 99, "physical": 98, "iq": 88, "team": "Real Madrid", "era": "2000s"},
    {"name": "Nuno Gomes", "position": "RB", "speed": 88, "dribbling": 71, "shooting": 54, "defense": 97, "physical": 92, "iq": 95, "team": "Napoli", "era": "2020s"},
    {"name": "Bobby Moore", "position": "LB", "speed": 82, "dribbling": 68, "shooting": 69, "defense": 96, "physical": 98, "iq": 96, "team": "Real Madrid", "era": "1930s"},
    {"name": "Aurélien Tchouaméni", "position": "CB", "speed": 82, "dribbling": 72, "shooting": 52, "defense": 94, "physical": 98, "iq": 98, "team": "AC Milan", "era": "1990s"},
    {"name": "Éder Militão", "position": "CB", "speed": 89, "dribbling": 74, "shooting": 45, "defense": 93, "physical": 94, "iq": 96, "team": "Inter Milan", "era": "1930s"},
    {"name": "Luizão", "position": "CB", "speed": 89, "dribbling": 65, "shooting": 65, "defense": 94, "physical": 94, "iq": 93, "team": "Paris SG", "era": "1980s"},
    {"name": "Irureta", "position": "CB", "speed": 80, "dribbling": 76, "shooting": 68, "defense": 97, "physical": 96, "iq": 93, "team": "Real Madrid", "era": "1930s"},
    {"name": "Causio", "position": "RB", "speed": 83, "dribbling": 67, "shooting": 50, "defense": 96, "physical": 95, "iq": 93, "team": "Inter Milan", "era": "2000s"},
    {"name": "João Cancelo", "position": "RB", "speed": 84, "dribbling": 65, "shooting": 67, "defense": 97, "physical": 89, "iq": 94, "team": "Inter Milan", "era": "1970s"},
    {"name": "Christian Benítez", "position": "CB", "speed": 83, "dribbling": 60, "shooting": 56, "defense": 96, "physical": 93, "iq": 92, "team": "Juventus", "era": "1930s"},
    {"name": "Edwin van der Sar", "position": "CB", "speed": 83, "dribbling": 76, "shooting": 62, "defense": 96, "physical": 90, "iq": 93, "team": "Barcelona", "era": "2020s"},
    {"name": "Andrea Pirlo", "position": "RB", "speed": 80, "dribbling": 71, "shooting": 54, "defense": 98, "physical": 94, "iq": 88, "team": "Juventus", "era": "2000s"},
    {"name": "Guillermo Ochoa", "position": "RB", "speed": 86, "dribbling": 76, "shooting": 56, "defense": 97, "physical": 94, "iq": 84, "team": "AC Milan", "era": "1970s"},
    {"name": "Rivaldo", "position": "LB", "speed": 90, "dribbling": 64, "shooting": 68, "defense": 97, "physical": 80, "iq": 94, "team": "Liverpool", "era": "2010s"},
    {"name": "Cicinho", "position": "RB", "speed": 80, "dribbling": 71, "shooting": 45, "defense": 96, "physical": 88, "iq": 97, "team": "AC Milan", "era": "1950s"},
    {"name": "Jorginho", "position": "RB", "speed": 77, "dribbling": 74, "shooting": 47, "defense": 97, "physical": 95, "iq": 91, "team": "Real Madrid", "era": "1950s"},
    {"name": "Roberto Carlos", "position": "LB", "speed": 82, "dribbling": 76, "shooting": 60, "defense": 96, "physical": 86, "iq": 97, "team": "Paris SG", "era": "2020s"},
    {"name": "Simone Diego", "position": "LB", "speed": 78, "dribbling": 65, "shooting": 52, "defense": 98, "physical": 94, "iq": 89, "team": "Inter Milan", "era": "1950s"},
    {"name": "Frank de Boer", "position": "CB", "speed": 78, "dribbling": 69, "shooting": 65, "defense": 99, "physical": 82, "iq": 98, "team": "Juventus", "era": "1970s"},
    {"name": "Héctor Yazalde", "position": "LB", "speed": 83, "dribbling": 62, "shooting": 61, "defense": 99, "physical": 95, "iq": 80, "team": "Inter Milan", "era": "1930s"},
    {"name": "Tomás Rincón", "position": "LB", "speed": 82, "dribbling": 60, "shooting": 55, "defense": 99, "physical": 81, "iq": 94, "team": "Inter Milan", "era": "2020s"},
    {"name": "Carlos Caszely", "position": "CB", "speed": 82, "dribbling": 76, "shooting": 62, "defense": 98, "physical": 98, "iq": 78, "team": "Liverpool", "era": "1950s"},
    {"name": "Radamel Falcao", "position": "RB", "speed": 84, "dribbling": 74, "shooting": 68, "defense": 89, "physical": 97, "iq": 95, "team": "Arsenal", "era": "1970s"},
    {"name": "Vinícius Júnior", "position": "RB", "speed": 90, "dribbling": 80, "shooting": 55, "defense": 88, "physical": 90, "iq": 98, "team": "Arsenal", "era": "2010s"},
    {"name": "Anísio", "position": "RB", "speed": 86, "dribbling": 65, "shooting": 47, "defense": 97, "physical": 83, "iq": 91, "team": "Paris SG", "era": "1930s"},
    {"name": "Arjen Robben", "position": "LB", "speed": 89, "dribbling": 69, "shooting": 60, "defense": 93, "physical": 87, "iq": 92, "team": "Barcelona", "era": "1990s"},
    {"name": "Javier Garay", "position": "CB", "speed": 81, "dribbling": 71, "shooting": 45, "defense": 98, "physical": 84, "iq": 92, "team": "Barcelona", "era": "2020s"},
    {"name": "Adriano Correia", "position": "CB", "speed": 76, "dribbling": 74, "shooting": 68, "defense": 95, "physical": 90, "iq": 97, "team": "Juventus", "era": "2020s"},
    {"name": "Falcao García", "position": "CB", "speed": 79, "dribbling": 69, "shooting": 45, "defense": 97, "physical": 88, "iq": 92, "team": "AC Milan", "era": "1930s"},
    {"name": "Gavira", "position": "RB", "speed": 82, "dribbling": 61, "shooting": 64, "defense": 96, "physical": 93, "iq": 86, "team": "Barcelona", "era": "1980s"},
    {"name": "Simão Sabrosa", "position": "RB", "speed": 81, "dribbling": 75, "shooting": 52, "defense": 95, "physical": 97, "iq": 85, "team": "Arsenal", "era": "2010s"},
    {"name": "Rune Bratseth", "position": "RB", "speed": 87, "dribbling": 66, "shooting": 50, "defense": 93, "physical": 85, "iq": 95, "team": "Juventus", "era": "1930s"},
    {"name": "Gilberto", "position": "RB", "speed": 90, "dribbling": 65, "shooting": 68, "defense": 89, "physical": 89, "iq": 96, "team": "Barcelona", "era": "1970s"},
    {"name": "Mario Mandžukić", "position": "LB", "speed": 90, "dribbling": 65, "shooting": 70, "defense": 95, "physical": 84, "iq": 89, "team": "Napoli", "era": "1930s"},
    {"name": "Uli Hoeness", "position": "LB", "speed": 89, "dribbling": 72, "shooting": 65, "defense": 87, "physical": 94, "iq": 96, "team": "Arsenal", "era": "1990s"},
    {"name": "Drogba", "position": "CB", "speed": 80, "dribbling": 62, "shooting": 50, "defense": 92, "physical": 94, "iq": 94, "team": "Real Madrid", "era": "1950s"},
    {"name": "Ousmane Dembélé", "position": "CB", "speed": 84, "dribbling": 62, "shooting": 45, "defense": 91, "physical": 89, "iq": 96, "team": "Arsenal", "era": "2020s"},
    {"name": "Giancarlo Antognoni", "position": "CB", "speed": 81, "dribbling": 75, "shooting": 53, "defense": 92, "physical": 94, "iq": 92, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Ederson", "position": "CB", "speed": 89, "dribbling": 76, "shooting": 54, "defense": 95, "physical": 75, "iq": 97, "team": "AC Milan", "era": "1970s"},
    {"name": "James Rodríguez", "position": "RB", "speed": 83, "dribbling": 61, "shooting": 48, "defense": 99, "physical": 77, "iq": 93, "team": "Inter Milan", "era": "2020s"},
    {"name": "de Bont", "position": "LB", "speed": 90, "dribbling": 75, "shooting": 53, "defense": 99, "physical": 79, "iq": 84, "team": "Real Madrid", "era": "2000s"},
    {"name": "Ronni Fernández", "position": "CB", "speed": 76, "dribbling": 70, "shooting": 69, "defense": 93, "physical": 94, "iq": 94, "team": "AC Milan", "era": "2010s"},
    {"name": "Aitor Karanka", "position": "CB", "speed": 88, "dribbling": 71, "shooting": 63, "defense": 91, "physical": 98, "iq": 82, "team": "AC Milan", "era": "2020s"},
    {"name": "Upamecano", "position": "CB", "speed": 88, "dribbling": 69, "shooting": 57, "defense": 98, "physical": 75, "iq": 91, "team": "Bayern Munich", "era": "1950s"},
    {"name": "Brian Laudrup", "position": "CB", "speed": 86, "dribbling": 66, "shooting": 65, "defense": 99, "physical": 79, "iq": 87, "team": "Inter Milan", "era": "2020s"},
    {"name": "Neeskens Johan", "position": "LB", "speed": 89, "dribbling": 71, "shooting": 51, "defense": 87, "physical": 94, "iq": 92, "team": "Juventus", "era": "2000s"},
    {"name": "Gentil", "position": "CB", "speed": 80, "dribbling": 71, "shooting": 53, "defense": 96, "physical": 81, "iq": 95, "team": "Inter Milan", "era": "1980s"},
    {"name": "Ramón Ábila", "position": "CB", "speed": 86, "dribbling": 80, "shooting": 57, "defense": 95, "physical": 94, "iq": 78, "team": "Manchester United", "era": "2010s"},
    {"name": "Nwankwo Kanu", "position": "RB", "speed": 89, "dribbling": 63, "shooting": 65, "defense": 87, "physical": 93, "iq": 92, "team": "Paris SG", "era": "1970s"},
    {"name": "Henning Berg", "position": "LB", "speed": 87, "dribbling": 67, "shooting": 55, "defense": 88, "physical": 88, "iq": 97, "team": "Inter Milan", "era": "1970s"},
    {"name": "Declan Rice", "position": "LB", "speed": 86, "dribbling": 76, "shooting": 52, "defense": 92, "physical": 97, "iq": 81, "team": "Napoli", "era": "2020s"},
    {"name": "Raheem Sterling", "position": "CB", "speed": 76, "dribbling": 79, "shooting": 69, "defense": 98, "physical": 91, "iq": 84, "team": "Juventus", "era": "2010s"},
    {"name": "Lionel Messi", "position": "CB", "speed": 89, "dribbling": 75, "shooting": 46, "defense": 86, "physical": 90, "iq": 96, "team": "Juventus", "era": "1950s"},
    {"name": "Andy Cole", "position": "CB", "speed": 80, "dribbling": 70, "shooting": 69, "defense": 93, "physical": 98, "iq": 83, "team": "Paris SG", "era": "1930s"},
    {"name": "Schaffino Juan", "position": "RB", "speed": 85, "dribbling": 68, "shooting": 67, "defense": 92, "physical": 90, "iq": 88, "team": "Napoli", "era": "1970s"},
    {"name": "Florian Wirtz", "position": "LB", "speed": 85, "dribbling": 80, "shooting": 61, "defense": 93, "physical": 98, "iq": 78, "team": "Real Madrid", "era": "1980s"},
    {"name": "József Bozsik", "position": "LB", "speed": 90, "dribbling": 74, "shooting": 59, "defense": 94, "physical": 78, "iq": 91, "team": "Inter Milan", "era": "1930s"},
    {"name": "Víctor Aristizábal", "position": "CB", "speed": 88, "dribbling": 68, "shooting": 47, "defense": 93, "physical": 83, "iq": 89, "team": "Chelsea", "era": "2010s"},
    {"name": "Niall Quinn", "position": "RB", "speed": 90, "dribbling": 80, "shooting": 50, "defense": 87, "physical": 84, "iq": 98, "team": "Barcelona", "era": "1970s"},
    {"name": "Rúben Dias", "position": "CB", "speed": 84, "dribbling": 78, "shooting": 55, "defense": 91, "physical": 95, "iq": 84, "team": "Real Madrid", "era": "1980s"},
    {"name": "John Aldridge", "position": "RB", "speed": 80, "dribbling": 62, "shooting": 62, "defense": 92, "physical": 93, "iq": 88, "team": "Chelsea", "era": "2000s"},
    {"name": "Julián Álvarez", "position": "CB", "speed": 88, "dribbling": 73, "shooting": 67, "defense": 89, "physical": 93, "iq": 85, "team": "Real Madrid", "era": "2000s"},
    {"name": "Flores", "position": "RB", "speed": 83, "dribbling": 78, "shooting": 52, "defense": 93, "physical": 95, "iq": 80, "team": "Liverpool", "era": "2010s"},
    {"name": "Fabinho", "position": "RB", "speed": 81, "dribbling": 69, "shooting": 50, "defense": 93, "physical": 83, "iq": 94, "team": "Barcelona", "era": "1990s"},
    {"name": "Héctor Enrique", "position": "LB", "speed": 82, "dribbling": 67, "shooting": 62, "defense": 94, "physical": 90, "iq": 84, "team": "Bayern Munich", "era": "1970s"},
    {"name": "Ever Banega", "position": "LB", "speed": 78, "dribbling": 68, "shooting": 45, "defense": 95, "physical": 86, "iq": 90, "team": "Arsenal", "era": "1970s"},
    {"name": "Gamarra", "position": "RB", "speed": 90, "dribbling": 79, "shooting": 69, "defense": 94, "physical": 77, "iq": 88, "team": "Arsenal", "era": "2010s"},
    {"name": "Juan Eduardo Hohberg", "position": "RB", "speed": 80, "dribbling": 68, "shooting": 59, "defense": 90, "physical": 89, "iq": 94, "team": "AC Milan", "era": "1950s"},
    {"name": "Jarrod Bowen", "position": "RB", "speed": 87, "dribbling": 79, "shooting": 54, "defense": 89, "physical": 86, "iq": 92, "team": "Arsenal", "era": "1930s"},
    {"name": "Marco Fabián", "position": "LB", "speed": 87, "dribbling": 64, "shooting": 70, "defense": 94, "physical": 80, "iq": 88, "team": "Manchester United", "era": "1930s"},
    {"name": "Moreno Juan", "position": "LB", "speed": 88, "dribbling": 75, "shooting": 48, "defense": 90, "physical": 93, "iq": 82, "team": "Liverpool", "era": "2000s"},
    {"name": "Néstor Vidrio", "position": "CB", "speed": 79, "dribbling": 64, "shooting": 50, "defense": 96, "physical": 87, "iq": 84, "team": "Manchester United", "era": "2010s"},
    {"name": "Gavi", "position": "RB", "speed": 90, "dribbling": 72, "shooting": 66, "defense": 94, "physical": 78, "iq": 86, "team": "Chelsea", "era": "2010s"},
    {"name": "Ryan Giggs", "position": "LB", "speed": 89, "dribbling": 76, "shooting": 58, "defense": 96, "physical": 77, "iq": 84, "team": "Real Madrid", "era": "2020s"},
    {"name": "Fabricio Fuentes", "position": "LB", "speed": 87, "dribbling": 70, "shooting": 56, "defense": 86, "physical": 87, "iq": 96, "team": "Juventus", "era": "2010s"},
    {"name": "Václav Hladký", "position": "CB", "speed": 90, "dribbling": 61, "shooting": 67, "defense": 93, "physical": 82, "iq": 83, "team": "Paris SG", "era": "2020s"},
    {"name": "Ferenc Szusza", "position": "RB", "speed": 87, "dribbling": 77, "shooting": 54, "defense": 90, "physical": 95, "iq": 79, "team": "Chelsea", "era": "1970s"},
    {"name": "Per Mertesacker", "position": "RB", "speed": 84, "dribbling": 69, "shooting": 61, "defense": 90, "physical": 81, "iq": 96, "team": "Arsenal", "era": "2000s"},
    {"name": "Sven-Göran Eriksson", "position": "RB", "speed": 77, "dribbling": 60, "shooting": 47, "defense": 90, "physical": 87, "iq": 97, "team": "Chelsea", "era": "1980s"},
    {"name": "Sergej Milinković-Savić", "position": "LB", "speed": 83, "dribbling": 72, "shooting": 53, "defense": 88, "physical": 91, "iq": 91, "team": "Arsenal", "era": "2010s"},
    {"name": "Graeme Souness", "position": "LB", "speed": 89, "dribbling": 64, "shooting": 49, "defense": 87, "physical": 90, "iq": 88, "team": "Liverpool", "era": "2000s"},
    {"name": "Marcus Rashford", "position": "LB", "speed": 79, "dribbling": 65, "shooting": 47, "defense": 91, "physical": 87, "iq": 93, "team": "Bayern Munich", "era": "2000s"},
    {"name": "Carlos Alberto Torres", "position": "CB", "speed": 83, "dribbling": 60, "shooting": 66, "defense": 91, "physical": 94, "iq": 81, "team": "Liverpool", "era": "1930s"},
    {"name": "Bukayo Saka", "position": "LB", "speed": 88, "dribbling": 72, "shooting": 61, "defense": 97, "physical": 76, "iq": 82, "team": "Inter Milan", "era": "1980s"},
    {"name": "Ronald Araújo", "position": "LB", "speed": 85, "dribbling": 68, "shooting": 47, "defense": 85, "physical": 87, "iq": 98, "team": "Napoli", "era": "1950s"},
    {"name": "Arturo Vidal", "position": "CB", "speed": 80, "dribbling": 79, "shooting": 70, "defense": 87, "physical": 96, "iq": 89, "team": "Paris SG", "era": "2010s"},
    {"name": "Peña", "position": "RB", "speed": 90, "dribbling": 70, "shooting": 62, "defense": 90, "physical": 90, "iq": 79, "team": "Manchester United", "era": "2010s"},
    {"name": "Gabriel Heinze", "position": "RB", "speed": 77, "dribbling": 73, "shooting": 60, "defense": 96, "physical": 76, "iq": 94, "team": "Arsenal", "era": "1980s"},
    {"name": "Olivier Kapo", "position": "LB", "speed": 84, "dribbling": 75, "shooting": 57, "defense": 91, "physical": 76, "iq": 97, "team": "AC Milan", "era": "1970s"},
    {"name": "Gerard Piqué", "position": "LB", "speed": 78, "dribbling": 72, "shooting": 56, "defense": 94, "physical": 93, "iq": 80, "team": "Liverpool", "era": "1930s"},
    {"name": "Matteo Darmian", "position": "LB", "speed": 81, "dribbling": 64, "shooting": 63, "defense": 97, "physical": 83, "iq": 81, "team": "Juventus", "era": "1990s"},
    {"name": "Garas", "position": "CB", "speed": 78, "dribbling": 62, "shooting": 56, "defense": 89, "physical": 90, "iq": 92, "team": "Manchester United", "era": "1970s"},
    {"name": "Raphaël Varane", "position": "CB", "speed": 81, "dribbling": 71, "shooting": 69, "defense": 96, "physical": 87, "iq": 78, "team": "Liverpool", "era": "1970s"},
    {"name": "Julio Comesaña", "position": "RB", "speed": 78, "dribbling": 63, "shooting": 49, "defense": 89, "physical": 94, "iq": 88, "team": "Arsenal", "era": "1950s"},
    {"name": "Christian Vieri", "position": "RB", "speed": 81, "dribbling": 62, "shooting": 45, "defense": 92, "physical": 82, "iq": 91, "team": "Paris SG", "era": "1980s"},
    {"name": "Arne Scheie", "position": "CB", "speed": 76, "dribbling": 67, "shooting": 65, "defense": 88, "physical": 98, "iq": 87, "team": "Napoli", "era": "1970s"},
    {"name": "Andrzej Szarmach", "position": "RB", "speed": 79, "dribbling": 77, "shooting": 60, "defense": 95, "physical": 83, "iq": 85, "team": "Barcelona", "era": "2020s"},
    {"name": "Marquinhos", "position": "LB", "speed": 83, "dribbling": 72, "shooting": 53, "defense": 93, "physical": 81, "iq": 87, "team": "Chelsea", "era": "1990s"},
    {"name": "Gonçalo Guedes", "position": "CB", "speed": 84, "dribbling": 65, "shooting": 65, "defense": 87, "physical": 84, "iq": 94, "team": "Liverpool", "era": "2020s"},
    {"name": "Antoine Griezmann", "position": "CB", "speed": 79, "dribbling": 66, "shooting": 65, "defense": 90, "physical": 88, "iq": 89, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Sergipe", "position": "CB", "speed": 79, "dribbling": 63, "shooting": 70, "defense": 90, "physical": 92, "iq": 85, "team": "Arsenal", "era": "2020s"},
    {"name": "David Lafata", "position": "RB", "speed": 88, "dribbling": 64, "shooting": 55, "defense": 90, "physical": 89, "iq": 79, "team": "Arsenal", "era": "1950s"},
    {"name": "Ilkay Gündoğan", "position": "RB", "speed": 78, "dribbling": 61, "shooting": 65, "defense": 99, "physical": 82, "iq": 78, "team": "Juventus", "era": "1950s"},
    {"name": "Alberto Rodríguez", "position": "RB", "speed": 76, "dribbling": 60, "shooting": 70, "defense": 91, "physical": 81, "iq": 97, "team": "Chelsea", "era": "1980s"},
    {"name": "Dwight Yorke", "position": "LB", "speed": 80, "dribbling": 73, "shooting": 47, "defense": 93, "physical": 76, "iq": 94, "team": "Liverpool", "era": "1980s"},
    {"name": "Muhren", "position": "LB", "speed": 78, "dribbling": 66, "shooting": 63, "defense": 88, "physical": 84, "iq": 98, "team": "Paris SG", "era": "1970s"},
    {"name": "Valentino Mazzola", "position": "CB", "speed": 80, "dribbling": 69, "shooting": 70, "defense": 91, "physical": 93, "iq": 80, "team": "Arsenal", "era": "2010s"},
    {"name": "Soren Lerby", "position": "RB", "speed": 81, "dribbling": 76, "shooting": 58, "defense": 87, "physical": 84, "iq": 96, "team": "Paris SG", "era": "1980s"},
    {"name": "Federico Bernardeschi", "position": "RB", "speed": 83, "dribbling": 74, "shooting": 54, "defense": 88, "physical": 79, "iq": 97, "team": "Arsenal", "era": "1930s"},
    {"name": "José de Paula", "position": "LB", "speed": 85, "dribbling": 61, "shooting": 63, "defense": 93, "physical": 86, "iq": 78, "team": "Napoli", "era": "2020s"},
    {"name": "Xavi Hernández", "position": "CB", "speed": 78, "dribbling": 63, "shooting": 68, "defense": 97, "physical": 76, "iq": 86, "team": "Arsenal", "era": "1990s"},
    {"name": "Alan Dzagoev", "position": "RB", "speed": 78, "dribbling": 71, "shooting": 57, "defense": 89, "physical": 91, "iq": 87, "team": "Chelsea", "era": "2000s"},
    {"name": "Laurent Blanc", "position": "CB", "speed": 88, "dribbling": 62, "shooting": 58, "defense": 89, "physical": 75, "iq": 92, "team": "Real Madrid", "era": "1980s"},
    {"name": "Marcelinho", "position": "CB", "speed": 86, "dribbling": 79, "shooting": 45, "defense": 89, "physical": 91, "iq": 78, "team": "Chelsea", "era": "1980s"},
    {"name": "Lacatus", "position": "RB", "speed": 76, "dribbling": 60, "shooting": 55, "defense": 86, "physical": 92, "iq": 93, "team": "Inter Milan", "era": "1970s"},
    {"name": "Mikel Merino", "position": "RB", "speed": 77, "dribbling": 63, "shooting": 48, "defense": 90, "physical": 93, "iq": 83, "team": "Inter Milan", "era": "2020s"},
    {"name": "Hidetoshi Nakata", "position": "LB", "speed": 90, "dribbling": 78, "shooting": 53, "defense": 88, "physical": 89, "iq": 78, "team": "Manchester United", "era": "1930s"},
    {"name": "Agne Simonsson", "position": "LB", "speed": 75, "dribbling": 64, "shooting": 65, "defense": 95, "physical": 75, "iq": 93, "team": "AC Milan", "era": "2000s"},
    {"name": "Jonbloed", "position": "CB", "speed": 87, "dribbling": 80, "shooting": 52, "defense": 87, "physical": 80, "iq": 91, "team": "Chelsea", "era": "1950s"},
    {"name": "Lima", "position": "CB", "speed": 80, "dribbling": 75, "shooting": 58, "defense": 92, "physical": 83, "iq": 85, "team": "Manchester United", "era": "1930s"},
    {"name": "Alessandro Nesta", "position": "LB", "speed": 89, "dribbling": 70, "shooting": 47, "defense": 85, "physical": 94, "iq": 79, "team": "Paris SG", "era": "2000s"},
    {"name": "Nils Liedholm", "position": "LB", "speed": 82, "dribbling": 79, "shooting": 57, "defense": 85, "physical": 92, "iq": 88, "team": "Barcelona", "era": "1950s"},
    {"name": "Alejandro Moreno", "position": "LB", "speed": 85, "dribbling": 60, "shooting": 58, "defense": 88, "physical": 82, "iq": 89, "team": "Real Madrid", "era": "1990s"},
    {"name": "Indio", "position": "LB", "speed": 78, "dribbling": 66, "shooting": 52, "defense": 92, "physical": 90, "iq": 80, "team": "Inter Milan", "era": "1950s"},
    {"name": "Włodzimierz Lubański", "position": "LB", "speed": 83, "dribbling": 68, "shooting": 63, "defense": 88, "physical": 80, "iq": 93, "team": "AC Milan", "era": "1950s"},
    {"name": "Gonzalo Higuaín", "position": "LB", "speed": 80, "dribbling": 68, "shooting": 47, "defense": 88, "physical": 97, "iq": 79, "team": "Real Madrid", "era": "2020s"},
    {"name": "Renato Tapia", "position": "CB", "speed": 84, "dribbling": 76, "shooting": 54, "defense": 87, "physical": 86, "iq": 87, "team": "Juventus", "era": "2010s"},
    {"name": "Matías Defederico", "position": "CB", "speed": 87, "dribbling": 69, "shooting": 54, "defense": 86, "physical": 90, "iq": 82, "team": "Napoli", "era": "1980s"},
    {"name": "Derlis González", "position": "CB", "speed": 83, "dribbling": 68, "shooting": 68, "defense": 86, "physical": 83, "iq": 93, "team": "Arsenal", "era": "1980s"},
    {"name": "Gunnar Nordahl", "position": "RB", "speed": 81, "dribbling": 67, "shooting": 45, "defense": 93, "physical": 81, "iq": 83, "team": "Real Madrid", "era": "1930s"},
    {"name": "Dejan Lovren", "position": "LB", "speed": 84, "dribbling": 70, "shooting": 62, "defense": 88, "physical": 75, "iq": 96, "team": "Manchester United", "era": "1970s"},
    {"name": "Michu", "position": "CB", "speed": 77, "dribbling": 68, "shooting": 60, "defense": 85, "physical": 85, "iq": 98, "team": "AC Milan", "era": "1980s"},
    {"name": "Ernesto Valverde", "position": "CB", "speed": 82, "dribbling": 79, "shooting": 66, "defense": 89, "physical": 87, "iq": 83, "team": "Real Madrid", "era": "2020s"},
    {"name": "Matthew Le Tissier", "position": "LB", "speed": 90, "dribbling": 63, "shooting": 55, "defense": 90, "physical": 77, "iq": 83, "team": "Juventus", "era": "1950s"},
    {"name": "Serginho", "position": "LB", "speed": 89, "dribbling": 64, "shooting": 64, "defense": 88, "physical": 82, "iq": 82, "team": "Bayern Munich", "era": "1980s"},
    {"name": "Arbeloa", "position": "RB", "speed": 78, "dribbling": 77, "shooting": 51, "defense": 85, "physical": 86, "iq": 94, "team": "Manchester United", "era": "1930s"},
    {"name": "Salomón Rondón", "position": "RB", "speed": 75, "dribbling": 70, "shooting": 69, "defense": 95, "physical": 82, "iq": 80, "team": "Arsenal", "era": "1970s"},
    {"name": "Lozano", "position": "LB", "speed": 84, "dribbling": 65, "shooting": 47, "defense": 92, "physical": 78, "iq": 80, "team": "Real Madrid", "era": "1990s"},
    {"name": "Maximiliano Meza", "position": "CB", "speed": 85, "dribbling": 77, "shooting": 56, "defense": 91, "physical": 79, "iq": 79, "team": "Arsenal", "era": "2020s"},
    {"name": "Emmanuel Adebayor", "position": "RB", "speed": 81, "dribbling": 61, "shooting": 54, "defense": 86, "physical": 82, "iq": 90, "team": "Chelsea", "era": "1930s"},
    {"name": "Hugo Lloris", "position": "RB", "speed": 79, "dribbling": 76, "shooting": 63, "defense": 86, "physical": 83, "iq": 91, "team": "Juventus", "era": "1990s"},
    {"name": "Franz Beckenbauer", "position": "RB", "speed": 82, "dribbling": 74, "shooting": 52, "defense": 86, "physical": 84, "iq": 87, "team": "Chelsea", "era": "1990s"},
    {"name": "Nélson Semedo", "position": "RB", "speed": 82, "dribbling": 64, "shooting": 50, "defense": 87, "physical": 84, "iq": 85, "team": "Juventus", "era": "1930s"},
    {"name": "Pauleta", "position": "LB", "speed": 79, "dribbling": 72, "shooting": 52, "defense": 90, "physical": 82, "iq": 84, "team": "Bayern Munich", "era": "1970s"},
    {"name": "Dinis", "position": "LB", "speed": 81, "dribbling": 76, "shooting": 56, "defense": 89, "physical": 75, "iq": 91, "team": "Juventus", "era": "1980s"},
    {"name": "Solskjær", "position": "RB", "speed": 80, "dribbling": 80, "shooting": 45, "defense": 87, "physical": 88, "iq": 82, "team": "Chelsea", "era": "1930s"},
    {"name": "Eduardo Camavinga", "position": "RB", "speed": 89, "dribbling": 64, "shooting": 55, "defense": 87, "physical": 82, "iq": 78, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Hugo Sánchez", "position": "RB", "speed": 79, "dribbling": 66, "shooting": 68, "defense": 85, "physical": 84, "iq": 90, "team": "Manchester United", "era": "1930s"},
    {"name": "Alisson", "position": "RB", "speed": 87, "dribbling": 73, "shooting": 56, "defense": 86, "physical": 84, "iq": 80, "team": "Barcelona", "era": "1970s"},
    {"name": "Canales", "position": "LB", "speed": 87, "dribbling": 66, "shooting": 56, "defense": 87, "physical": 82, "iq": 80, "team": "AC Milan", "era": "2000s"},
    {"name": "Haan Erwin", "position": "CB", "speed": 82, "dribbling": 73, "shooting": 53, "defense": 85, "physical": 81, "iq": 89, "team": "Napoli", "era": "1950s"},
    {"name": "Frederic Kanoute", "position": "RB", "speed": 75, "dribbling": 64, "shooting": 61, "defense": 88, "physical": 83, "iq": 88, "team": "Manchester United", "era": "1950s"},
    {"name": "Claude Makélélé", "position": "LB", "speed": 76, "dribbling": 67, "shooting": 45, "defense": 96, "physical": 75, "iq": 78, "team": "Paris SG", "era": "1950s"},
    {"name": "Yuri Zhirkov", "position": "LB", "speed": 77, "dribbling": 79, "shooting": 53, "defense": 85, "physical": 96, "iq": 78, "team": "AC Milan", "era": "1970s"},
    {"name": "Jerzy Sidor", "position": "CB", "speed": 80, "dribbling": 70, "shooting": 46, "defense": 91, "physical": 77, "iq": 81, "team": "Napoli", "era": "1970s"},
    {"name": "Romário", "position": "RB", "speed": 78, "dribbling": 60, "shooting": 49, "defense": 85, "physical": 82, "iq": 90, "team": "Juventus", "era": "1930s"},
    {"name": "Héctor Bellerín", "position": "LB", "speed": 79, "dribbling": 79, "shooting": 62, "defense": 89, "physical": 76, "iq": 87, "team": "Arsenal", "era": "1990s"},
    {"name": "Dolso", "position": "RB", "speed": 86, "dribbling": 78, "shooting": 45, "defense": 86, "physical": 83, "iq": 78, "team": "Manchester United", "era": "1980s"},
    {"name": "Edson Puch", "position": "CB", "speed": 82, "dribbling": 62, "shooting": 50, "defense": 85, "physical": 84, "iq": 82, "team": "Chelsea", "era": "1970s"},
    {"name": "Ferran Torres", "position": "LB", "speed": 80, "dribbling": 78, "shooting": 48, "defense": 86, "physical": 78, "iq": 87, "team": "Juventus", "era": "2020s"},
    {"name": "Robinho", "position": "CB", "speed": 76, "dribbling": 62, "shooting": 62, "defense": 86, "physical": 83, "iq": 85, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Rossi", "position": "LB", "speed": 75, "dribbling": 77, "shooting": 47, "defense": 88, "physical": 85, "iq": 79, "team": "Inter Milan", "era": "1980s"},
    {"name": "Gómez", "position": "CB", "speed": 78, "dribbling": 73, "shooting": 46, "defense": 88, "physical": 75, "iq": 80, "team": "Chelsea", "era": "1970s"},
    {"name": "Didier Drogba", "position": "LB", "speed": 76, "dribbling": 65, "shooting": 61, "defense": 87, "physical": 81, "iq": 78, "team": "Manchester United", "era": "2000s"},
]

def get_defenders():
    """Return all defenders"""
    return DEFENDERS
