"""Hermaniland - Delanteros (Forwards) Database"""

FORWARDS = [
    {"name": "Deco", "position": "ST", "speed": 94, "dribbling": 92, "shooting": 98, "defense": 56, "physical": 95, "iq": 85, "team": "Juventus", "era": "1950s"},
    {"name": "Carlos Salcido", "position": "LW", "speed": 91, "dribbling": 92, "shooting": 97, "defense": 26, "physical": 98, "iq": 97, "team": "Barcelona", "era": "2000s"},
    {"name": "Gilmar", "position": "ST", "speed": 96, "dribbling": 90, "shooting": 97, "defense": 50, "physical": 93, "iq": 82, "team": "Bayern Munich", "era": "2020s"},
    {"name": "Vérissimo", "position": "LW", "speed": 95, "dribbling": 90, "shooting": 97, "defense": 38, "physical": 94, "iq": 90, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Dennis Bergkamp", "position": "LW", "speed": 94, "dribbling": 86, "shooting": 98, "defense": 43, "physical": 97, "iq": 81, "team": "Paris SG", "era": "1950s"},
    {"name": "Carlos", "position": "ST", "speed": 93, "dribbling": 86, "shooting": 97, "defense": 25, "physical": 97, "iq": 97, "team": "Arsenal", "era": "2000s"},
    {"name": "Cafu", "position": "LW", "speed": 90, "dribbling": 94, "shooting": 94, "defense": 33, "physical": 97, "iq": 98, "team": "Manchester United", "era": "1970s"},
    {"name": "Jody Loyola", "position": "LW", "speed": 95, "dribbling": 85, "shooting": 95, "defense": 60, "physical": 98, "iq": 95, "team": "Chelsea", "era": "1970s"},
    {"name": "Youri Djorkaeff", "position": "ST", "speed": 92, "dribbling": 89, "shooting": 98, "defense": 45, "physical": 90, "iq": 79, "team": "Paris SG", "era": "2020s"},
    {"name": "Paenza Ariel", "position": "LW", "speed": 91, "dribbling": 87, "shooting": 98, "defense": 34, "physical": 93, "iq": 97, "team": "AC Milan", "era": "1950s"},
    {"name": "Bobby Charlton", "position": "LW", "speed": 88, "dribbling": 89, "shooting": 97, "defense": 47, "physical": 94, "iq": 91, "team": "Juventus", "era": "2000s"},
    {"name": "Julio Cesar", "position": "ST", "speed": 86, "dribbling": 94, "shooting": 93, "defense": 42, "physical": 98, "iq": 98, "team": "Manchester United", "era": "1930s"},
    {"name": "Zamorano", "position": "ST", "speed": 85, "dribbling": 87, "shooting": 97, "defense": 46, "physical": 98, "iq": 88, "team": "Juventus", "era": "1930s"},
    {"name": "Julen Guerrero", "position": "LW", "speed": 93, "dribbling": 91, "shooting": 98, "defense": 25, "physical": 83, "iq": 81, "team": "Paris SG", "era": "2000s"},
    {"name": "Harry Kane", "position": "ST", "speed": 96, "dribbling": 82, "shooting": 95, "defense": 34, "physical": 93, "iq": 94, "team": "Chelsea", "era": "2010s"},
    {"name": "Ronny", "position": "LW", "speed": 89, "dribbling": 87, "shooting": 95, "defense": 33, "physical": 94, "iq": 80, "team": "Chelsea", "era": "2010s"},
    {"name": "Iker Casillas", "position": "ST", "speed": 90, "dribbling": 93, "shooting": 92, "defense": 38, "physical": 92, "iq": 97, "team": "Inter Milan", "era": "1930s"},
    {"name": "Jorge Ávalos", "position": "ST", "speed": 96, "dribbling": 88, "shooting": 98, "defense": 34, "physical": 79, "iq": 87, "team": "Barcelona", "era": "1990s"},
    {"name": "Oscar Cardozo", "position": "ST", "speed": 94, "dribbling": 92, "shooting": 90, "defense": 33, "physical": 93, "iq": 81, "team": "Liverpool", "era": "2000s"},
    {"name": "Lucio", "position": "LW", "speed": 92, "dribbling": 75, "shooting": 98, "defense": 47, "physical": 96, "iq": 98, "team": "Chelsea", "era": "1930s"},
    {"name": "Dąbrowski", "position": "LW", "speed": 94, "dribbling": 90, "shooting": 97, "defense": 26, "physical": 80, "iq": 88, "team": "Juventus", "era": "1950s"},
    {"name": "Mesut Özil", "position": "LW", "speed": 94, "dribbling": 81, "shooting": 92, "defense": 47, "physical": 98, "iq": 80, "team": "Barcelona", "era": "2010s"},
    {"name": "Puyol", "position": "LW", "speed": 90, "dribbling": 83, "shooting": 94, "defense": 60, "physical": 96, "iq": 83, "team": "Arsenal", "era": "1930s"},
    {"name": "Ronald de Boer", "position": "ST", "speed": 86, "dribbling": 80, "shooting": 96, "defense": 28, "physical": 98, "iq": 94, "team": "Napoli", "era": "2000s"},
    {"name": "César Azpilicueta", "position": "ST", "speed": 88, "dribbling": 94, "shooting": 97, "defense": 58, "physical": 80, "iq": 89, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Zé Maria", "position": "ST", "speed": 89, "dribbling": 93, "shooting": 91, "defense": 28, "physical": 92, "iq": 88, "team": "Real Madrid", "era": "2010s"},
    {"name": "Thiago Alcántara", "position": "ST", "speed": 84, "dribbling": 89, "shooting": 93, "defense": 55, "physical": 96, "iq": 79, "team": "Chelsea", "era": "1980s"},
    {"name": "Igor Akinfeev", "position": "ST", "speed": 94, "dribbling": 88, "shooting": 98, "defense": 48, "physical": 77, "iq": 91, "team": "Manchester United", "era": "1970s"},
    {"name": "Gianluigi Buffon", "position": "LW", "speed": 93, "dribbling": 94, "shooting": 88, "defense": 34, "physical": 92, "iq": 92, "team": "Chelsea", "era": "1980s"},
    {"name": "Raí", "position": "ST", "speed": 91, "dribbling": 92, "shooting": 91, "defense": 58, "physical": 89, "iq": 95, "team": "Real Madrid", "era": "2000s"},
    {"name": "Gyorgy Sarosi", "position": "LW", "speed": 91, "dribbling": 94, "shooting": 90, "defense": 47, "physical": 89, "iq": 83, "team": "Chelsea", "era": "2010s"},
    {"name": "Scarone", "position": "ST", "speed": 87, "dribbling": 95, "shooting": 94, "defense": 56, "physical": 83, "iq": 96, "team": "Liverpool", "era": "2020s"},
    {"name": "Serge Gnabry", "position": "LW", "speed": 87, "dribbling": 81, "shooting": 94, "defense": 58, "physical": 97, "iq": 82, "team": "Manchester United", "era": "2020s"},
    {"name": "Pinto da Costa", "position": "LW", "speed": 95, "dribbling": 83, "shooting": 91, "defense": 28, "physical": 93, "iq": 81, "team": "Inter Milan", "era": "2020s"},
    {"name": "Raúl González", "position": "ST", "speed": 93, "dribbling": 81, "shooting": 97, "defense": 60, "physical": 84, "iq": 85, "team": "Manchester United", "era": "1930s"},
    {"name": "Fernandinho", "position": "LW", "speed": 92, "dribbling": 86, "shooting": 89, "defense": 25, "physical": 96, "iq": 92, "team": "Real Madrid", "era": "1930s"},
    {"name": "Patrick Vieira", "position": "LW", "speed": 85, "dribbling": 87, "shooting": 93, "defense": 43, "physical": 94, "iq": 92, "team": "Arsenal", "era": "2000s"},
    {"name": "Kazuyoshi Miura", "position": "LW", "speed": 91, "dribbling": 92, "shooting": 91, "defense": 30, "physical": 87, "iq": 82, "team": "Barcelona", "era": "1970s"},
    {"name": "Karl-Heinz Förster", "position": "ST", "speed": 88, "dribbling": 86, "shooting": 93, "defense": 32, "physical": 91, "iq": 89, "team": "Paris SG", "era": "1970s"},
    {"name": "Jérôme Boateng", "position": "LW", "speed": 83, "dribbling": 87, "shooting": 97, "defense": 55, "physical": 87, "iq": 90, "team": "Juventus", "era": "1930s"},
    {"name": "Víctor Valdés", "position": "LW", "speed": 84, "dribbling": 87, "shooting": 93, "defense": 58, "physical": 94, "iq": 92, "team": "Arsenal", "era": "2000s"},
    {"name": "René Higuita", "position": "ST", "speed": 84, "dribbling": 87, "shooting": 94, "defense": 29, "physical": 91, "iq": 83, "team": "AC Milan", "era": "1950s"},
    {"name": "René Houseman", "position": "ST", "speed": 92, "dribbling": 90, "shooting": 93, "defense": 25, "physical": 82, "iq": 97, "team": "Liverpool", "era": "2020s"},
    {"name": "Édison Méndez", "position": "ST", "speed": 82, "dribbling": 87, "shooting": 94, "defense": 48, "physical": 93, "iq": 97, "team": "Liverpool", "era": "2000s"},
    {"name": "Sylvain Wiltord", "position": "LW", "speed": 92, "dribbling": 94, "shooting": 86, "defense": 60, "physical": 92, "iq": 84, "team": "Juventus", "era": "1990s"},
    {"name": "Arango Juan", "position": "LW", "speed": 96, "dribbling": 89, "shooting": 89, "defense": 38, "physical": 86, "iq": 87, "team": "Barcelona", "era": "1950s"},
    {"name": "Frank Lampard", "position": "LW", "speed": 96, "dribbling": 77, "shooting": 94, "defense": 53, "physical": 88, "iq": 80, "team": "Chelsea", "era": "1970s"},
    {"name": "Xabi Alonso", "position": "LW", "speed": 89, "dribbling": 79, "shooting": 97, "defense": 35, "physical": 86, "iq": 85, "team": "Paris SG", "era": "1950s"},
    {"name": "Marchena", "position": "ST", "speed": 89, "dribbling": 86, "shooting": 90, "defense": 33, "physical": 92, "iq": 92, "team": "Napoli", "era": "1970s"},
    {"name": "João Moutinho", "position": "ST", "speed": 94, "dribbling": 78, "shooting": 89, "defense": 49, "physical": 97, "iq": 81, "team": "Manchester United", "era": "1930s"},
    {"name": "Subert", "position": "ST", "speed": 94, "dribbling": 90, "shooting": 94, "defense": 48, "physical": 75, "iq": 98, "team": "Manchester United", "era": "2020s"},
    {"name": "Anthony Martial", "position": "ST", "speed": 86, "dribbling": 89, "shooting": 95, "defense": 34, "physical": 82, "iq": 78, "team": "Chelsea", "era": "2020s"},
    {"name": "Andrés Iniesta", "position": "LW", "speed": 92, "dribbling": 87, "shooting": 90, "defense": 56, "physical": 88, "iq": 87, "team": "Bayern Munich", "era": "2020s"},
    {"name": "Jaap Stam", "position": "LW", "speed": 95, "dribbling": 78, "shooting": 88, "defense": 35, "physical": 98, "iq": 83, "team": "AC Milan", "era": "2010s"},
    {"name": "Tostão", "position": "LW", "speed": 94, "dribbling": 85, "shooting": 92, "defense": 55, "physical": 84, "iq": 93, "team": "Paris SG", "era": "1970s"},
    {"name": "Sforza", "position": "LW", "speed": 95, "dribbling": 78, "shooting": 88, "defense": 58, "physical": 98, "iq": 80, "team": "Juventus", "era": "2000s"},
    {"name": "Alessio Romagnoli", "position": "ST", "speed": 83, "dribbling": 89, "shooting": 94, "defense": 43, "physical": 86, "iq": 97, "team": "Paris SG", "era": "2010s"},
    {"name": "Antonín Panenka", "position": "LW", "speed": 90, "dribbling": 90, "shooting": 85, "defense": 36, "physical": 96, "iq": 81, "team": "Chelsea", "era": "2020s"},
    {"name": "Achraf Hakimi", "position": "LW", "speed": 83, "dribbling": 89, "shooting": 97, "defense": 29, "physical": 80, "iq": 94, "team": "Chelsea", "era": "1950s"},
    {"name": "Francisco Cerro", "position": "ST", "speed": 86, "dribbling": 82, "shooting": 97, "defense": 37, "physical": 83, "iq": 89, "team": "AC Milan", "era": "2020s"},
    {"name": "Mario Gómez", "position": "ST", "speed": 93, "dribbling": 77, "shooting": 95, "defense": 27, "physical": 85, "iq": 97, "team": "Arsenal", "era": "1990s"},
    {"name": "Rogelio Delgado", "position": "LW", "speed": 92, "dribbling": 95, "shooting": 87, "defense": 44, "physical": 84, "iq": 92, "team": "Bayern Munich", "era": "2010s"},
    {"name": "Jamal Musiala", "position": "LW", "speed": 87, "dribbling": 88, "shooting": 89, "defense": 36, "physical": 92, "iq": 82, "team": "Bayern Munich", "era": "2010s"},
    {"name": "Benjamin Pavard", "position": "LW", "speed": 95, "dribbling": 75, "shooting": 94, "defense": 27, "physical": 87, "iq": 91, "team": "Barcelona", "era": "1950s"},
    {"name": "Iñigo Martínez", "position": "ST", "speed": 95, "dribbling": 77, "shooting": 89, "defense": 42, "physical": 93, "iq": 89, "team": "Juventus", "era": "1990s"},
    {"name": "Frank Rijkaard", "position": "ST", "speed": 93, "dribbling": 83, "shooting": 95, "defense": 47, "physical": 77, "iq": 91, "team": "Bayern Munich", "era": "1950s"},
    {"name": "Jesús Navas", "position": "ST", "speed": 91, "dribbling": 88, "shooting": 92, "defense": 51, "physical": 80, "iq": 84, "team": "AC Milan", "era": "2010s"},
    {"name": "Andrés Guardado", "position": "ST", "speed": 89, "dribbling": 95, "shooting": 82, "defense": 31, "physical": 95, "iq": 89, "team": "Paris SG", "era": "1980s"},
    {"name": "Adalberto Martínez", "position": "ST", "speed": 91, "dribbling": 89, "shooting": 88, "defense": 50, "physical": 87, "iq": 96, "team": "Barcelona", "era": "2020s"},
    {"name": "Julio Cáseres", "position": "LW", "speed": 93, "dribbling": 79, "shooting": 95, "defense": 42, "physical": 81, "iq": 86, "team": "Real Madrid", "era": "1980s"},
    {"name": "Yasuhito Endo", "position": "LW", "speed": 94, "dribbling": 81, "shooting": 88, "defense": 45, "physical": 92, "iq": 94, "team": "Barcelona", "era": "1930s"},
    {"name": "Poborský", "position": "ST", "speed": 89, "dribbling": 86, "shooting": 93, "defense": 30, "physical": 81, "iq": 97, "team": "Manchester United", "era": "1970s"},
    {"name": "Cassano", "position": "ST", "speed": 90, "dribbling": 79, "shooting": 89, "defense": 57, "physical": 95, "iq": 79, "team": "Juventus", "era": "1930s"},
    {"name": "Paul Breitner", "position": "ST", "speed": 88, "dribbling": 88, "shooting": 86, "defense": 27, "physical": 94, "iq": 87, "team": "Manchester United", "era": "1980s"},
    {"name": "Mihaly Pataki", "position": "ST", "speed": 85, "dribbling": 86, "shooting": 94, "defense": 42, "physical": 83, "iq": 78, "team": "Manchester United", "era": "1970s"},
    {"name": "Raúl Ruidíaz", "position": "ST", "speed": 88, "dribbling": 94, "shooting": 92, "defense": 45, "physical": 76, "iq": 92, "team": "AC Milan", "era": "2010s"},
    {"name": "Leopoldo Jacinto Luque", "position": "LW", "speed": 84, "dribbling": 94, "shooting": 92, "defense": 42, "physical": 80, "iq": 83, "team": "Napoli", "era": "2010s"},
    {"name": "Espinoza", "position": "LW", "speed": 95, "dribbling": 92, "shooting": 87, "defense": 58, "physical": 81, "iq": 80, "team": "Napoli", "era": "2000s"},
    {"name": "Sepp Maier", "position": "LW", "speed": 91, "dribbling": 92, "shooting": 91, "defense": 31, "physical": 77, "iq": 80, "team": "Inter Milan", "era": "1990s"},
    {"name": "Óscar Más", "position": "ST", "speed": 94, "dribbling": 76, "shooting": 97, "defense": 49, "physical": 77, "iq": 98, "team": "Manchester United", "era": "1950s"},
    {"name": "Rüdiger", "position": "ST", "speed": 88, "dribbling": 90, "shooting": 87, "defense": 36, "physical": 89, "iq": 89, "team": "Inter Milan", "era": "1990s"},
    {"name": "Sergi Roberto", "position": "LW", "speed": 94, "dribbling": 85, "shooting": 82, "defense": 59, "physical": 98, "iq": 98, "team": "Bayern Munich", "era": "2020s"},
    {"name": "Darren Anderton", "position": "LW", "speed": 88, "dribbling": 92, "shooting": 85, "defense": 26, "physical": 91, "iq": 94, "team": "Liverpool", "era": "1970s"},
    {"name": "Sami Khedira", "position": "LW", "speed": 94, "dribbling": 80, "shooting": 90, "defense": 53, "physical": 87, "iq": 89, "team": "Bayern Munich", "era": "1930s"},
    {"name": "Sérgio Brisante", "position": "ST", "speed": 88, "dribbling": 75, "shooting": 92, "defense": 55, "physical": 93, "iq": 91, "team": "AC Milan", "era": "1980s"},
    {"name": "Martín Demichelis", "position": "ST", "speed": 92, "dribbling": 80, "shooting": 94, "defense": 39, "physical": 80, "iq": 86, "team": "Inter Milan", "era": "2020s"},
    {"name": "Valdez", "position": "LW", "speed": 83, "dribbling": 77, "shooting": 97, "defense": 32, "physical": 86, "iq": 87, "team": "AC Milan", "era": "1980s"},
    {"name": "Salas", "position": "LW", "speed": 84, "dribbling": 76, "shooting": 97, "defense": 26, "physical": 86, "iq": 83, "team": "Liverpool", "era": "2000s"},
    {"name": "Giacinto Facchetti", "position": "ST", "speed": 94, "dribbling": 81, "shooting": 87, "defense": 51, "physical": 90, "iq": 80, "team": "Barcelona", "era": "2020s"},
    {"name": "Gianni Rivera", "position": "LW", "speed": 93, "dribbling": 94, "shooting": 84, "defense": 29, "physical": 84, "iq": 86, "team": "Real Madrid", "era": "2010s"},
    {"name": "Marcus Tutte", "position": "LW", "speed": 87, "dribbling": 88, "shooting": 91, "defense": 40, "physical": 82, "iq": 89, "team": "Juventus", "era": "1970s"},
    {"name": "Wim Jansen", "position": "ST", "speed": 85, "dribbling": 82, "shooting": 88, "defense": 52, "physical": 95, "iq": 98, "team": "Arsenal", "era": "1970s"},
    {"name": "Verratti", "position": "ST", "speed": 96, "dribbling": 80, "shooting": 93, "defense": 38, "physical": 76, "iq": 90, "team": "Arsenal", "era": "1950s"},
    {"name": "Jan Koller", "position": "LW", "speed": 86, "dribbling": 81, "shooting": 98, "defense": 37, "physical": 75, "iq": 94, "team": "Chelsea", "era": "1980s"},
    {"name": "Samuel Castillejos", "position": "LW", "speed": 86, "dribbling": 87, "shooting": 84, "defense": 27, "physical": 97, "iq": 82, "team": "AC Milan", "era": "1970s"},
    {"name": "Ben White", "position": "ST", "speed": 84, "dribbling": 82, "shooting": 89, "defense": 28, "physical": 93, "iq": 87, "team": "Chelsea", "era": "2010s"},
    {"name": "Ian Wright", "position": "ST", "speed": 96, "dribbling": 75, "shooting": 90, "defense": 44, "physical": 86, "iq": 78, "team": "Juventus", "era": "2020s"},
    {"name": "Leonardo Valencia", "position": "LW", "speed": 90, "dribbling": 79, "shooting": 95, "defense": 27, "physical": 78, "iq": 95, "team": "Paris SG", "era": "2020s"},
    {"name": "Nándor Hidegkuti", "position": "LW", "speed": 89, "dribbling": 95, "shooting": 86, "defense": 39, "physical": 81, "iq": 84, "team": "Juventus", "era": "1930s"},
    {"name": "Rafael Márquez", "position": "LW", "speed": 90, "dribbling": 86, "shooting": 92, "defense": 36, "physical": 77, "iq": 86, "team": "Liverpool", "era": "1930s"},
    {"name": "Laporte", "position": "ST", "speed": 95, "dribbling": 75, "shooting": 89, "defense": 45, "physical": 88, "iq": 79, "team": "Real Madrid", "era": "1930s"},
    {"name": "Santiago Tapia", "position": "ST", "speed": 89, "dribbling": 85, "shooting": 82, "defense": 27, "physical": 98, "iq": 84, "team": "AC Milan", "era": "1990s"},
    {"name": "Phil Foden", "position": "LW", "speed": 85, "dribbling": 93, "shooting": 91, "defense": 29, "physical": 76, "iq": 81, "team": "Arsenal", "era": "1990s"},
    {"name": "Roque Junior", "position": "ST", "speed": 91, "dribbling": 91, "shooting": 85, "defense": 54, "physical": 83, "iq": 78, "team": "Bayern Munich", "era": "1950s"},
    {"name": "Almeyda", "position": "ST", "speed": 83, "dribbling": 88, "shooting": 94, "defense": 40, "physical": 76, "iq": 91, "team": "Napoli", "era": "2020s"},
    {"name": "Pedri González", "position": "LW", "speed": 82, "dribbling": 87, "shooting": 93, "defense": 52, "physical": 80, "iq": 84, "team": "Paris SG", "era": "1970s"},
    {"name": "Vera", "position": "LW", "speed": 89, "dribbling": 94, "shooting": 84, "defense": 27, "physical": 84, "iq": 80, "team": "Inter Milan", "era": "1990s"},
    {"name": "Alberto Tarantini", "position": "ST", "speed": 91, "dribbling": 75, "shooting": 96, "defense": 38, "physical": 76, "iq": 89, "team": "Liverpool", "era": "2010s"},
    {"name": "Christoph Metzelder", "position": "LW", "speed": 94, "dribbling": 88, "shooting": 83, "defense": 27, "physical": 86, "iq": 79, "team": "Arsenal", "era": "2020s"},
    {"name": "Henning Jensen", "position": "LW", "speed": 96, "dribbling": 89, "shooting": 85, "defense": 46, "physical": 79, "iq": 79, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Fabrice Barthez", "position": "LW", "speed": 87, "dribbling": 79, "shooting": 88, "defense": 35, "physical": 92, "iq": 97, "team": "Manchester United", "era": "2020s"},
    {"name": "Ziober", "position": "ST", "speed": 82, "dribbling": 78, "shooting": 95, "defense": 55, "physical": 83, "iq": 79, "team": "Arsenal", "era": "1930s"},
    {"name": "Álex Ibacache", "position": "ST", "speed": 90, "dribbling": 77, "shooting": 94, "defense": 37, "physical": 78, "iq": 98, "team": "Paris SG", "era": "2000s"},
    {"name": "Leônidas da Silva", "position": "LW", "speed": 92, "dribbling": 81, "shooting": 84, "defense": 49, "physical": 92, "iq": 85, "team": "Inter Milan", "era": "1970s"},
    {"name": "Åke Liedholm", "position": "LW", "speed": 88, "dribbling": 87, "shooting": 88, "defense": 32, "physical": 82, "iq": 98, "team": "Juventus", "era": "1970s"},
    {"name": "Gerd Müller", "position": "ST", "speed": 86, "dribbling": 86, "shooting": 92, "defense": 47, "physical": 76, "iq": 83, "team": "Real Madrid", "era": "1990s"},
    {"name": "Enner Valencia", "position": "LW", "speed": 86, "dribbling": 75, "shooting": 93, "defense": 37, "physical": 85, "iq": 80, "team": "Juventus", "era": "2010s"},
    {"name": "Osvaldo Ardiles", "position": "LW", "speed": 90, "dribbling": 81, "shooting": 87, "defense": 35, "physical": 87, "iq": 92, "team": "AC Milan", "era": "1980s"},
    {"name": "Paquetá", "position": "LW", "speed": 88, "dribbling": 79, "shooting": 87, "defense": 26, "physical": 91, "iq": 83, "team": "Arsenal", "era": "2020s"},
    {"name": "Sorín Juan Pablo", "position": "ST", "speed": 92, "dribbling": 80, "shooting": 91, "defense": 38, "physical": 77, "iq": 84, "team": "Real Madrid", "era": "1990s"},
    {"name": "Robert Pires", "position": "ST", "speed": 91, "dribbling": 95, "shooting": 84, "defense": 27, "physical": 77, "iq": 79, "team": "Bayern Munich", "era": "1950s"},
    {"name": "Jair Bolívar", "position": "ST", "speed": 92, "dribbling": 92, "shooting": 82, "defense": 56, "physical": 83, "iq": 89, "team": "Bayern Munich", "era": "2000s"},
    {"name": "Sándor Kocsis", "position": "ST", "speed": 90, "dribbling": 83, "shooting": 83, "defense": 54, "physical": 92, "iq": 79, "team": "Manchester United", "era": "1970s"},
    {"name": "Elano", "position": "LW", "speed": 92, "dribbling": 88, "shooting": 87, "defense": 32, "physical": 77, "iq": 93, "team": "AC Milan", "era": "1950s"},
    {"name": "Pedro Bergara", "position": "LW", "speed": 87, "dribbling": 93, "shooting": 83, "defense": 37, "physical": 85, "iq": 81, "team": "Arsenal", "era": "1980s"},
    {"name": "Alberto Gilardino", "position": "LW", "speed": 83, "dribbling": 78, "shooting": 97, "defense": 56, "physical": 76, "iq": 79, "team": "Real Madrid", "era": "1990s"},
    {"name": "Jordi Alba", "position": "ST", "speed": 83, "dribbling": 80, "shooting": 92, "defense": 36, "physical": 83, "iq": 88, "team": "Paris SG", "era": "1930s"},
    {"name": "Jorge Valdano", "position": "LW", "speed": 82, "dribbling": 80, "shooting": 94, "defense": 38, "physical": 80, "iq": 83, "team": "Inter Milan", "era": "2010s"},
    {"name": "Zagallo", "position": "ST", "speed": 85, "dribbling": 84, "shooting": 85, "defense": 41, "physical": 90, "iq": 85, "team": "Paris SG", "era": "1950s"},
    {"name": "Karel Novák", "position": "LW", "speed": 93, "dribbling": 80, "shooting": 88, "defense": 39, "physical": 80, "iq": 81, "team": "Barcelona", "era": "2000s"},
    {"name": "Kylian Mbappé", "position": "ST", "speed": 94, "dribbling": 77, "shooting": 83, "defense": 27, "physical": 91, "iq": 83, "team": "Manchester United", "era": "2020s"},
    {"name": "Pelé", "position": "ST", "speed": 87, "dribbling": 80, "shooting": 84, "defense": 41, "physical": 92, "iq": 88, "team": "Manchester United", "era": "1990s"},
    {"name": "Ronaldo Nazário", "position": "LW", "speed": 86, "dribbling": 85, "shooting": 85, "defense": 30, "physical": 86, "iq": 84, "team": "Manchester United", "era": "1930s"},
    {"name": "Manuel Neuer", "position": "ST", "speed": 82, "dribbling": 80, "shooting": 83, "defense": 54, "physical": 98, "iq": 83, "team": "Bayern Munich", "era": "1980s"},
    {"name": "Sorin", "position": "ST", "speed": 90, "dribbling": 93, "shooting": 83, "defense": 29, "physical": 77, "iq": 88, "team": "Liverpool", "era": "2000s"},
    {"name": "Ove Kindvall", "position": "ST", "speed": 85, "dribbling": 87, "shooting": 87, "defense": 59, "physical": 80, "iq": 98, "team": "Paris SG", "era": "1990s"},
    {"name": "Alberto Rodríguez Larreta", "position": "LW", "speed": 94, "dribbling": 75, "shooting": 84, "defense": 37, "physical": 89, "iq": 79, "team": "Inter Milan", "era": "2020s"},
    {"name": "Carlos Gruezo", "position": "LW", "speed": 85, "dribbling": 78, "shooting": 84, "defense": 36, "physical": 94, "iq": 88, "team": "Juventus", "era": "1930s"},
    {"name": "Karl-Heinz Rummenigge", "position": "LW", "speed": 85, "dribbling": 81, "shooting": 87, "defense": 55, "physical": 85, "iq": 98, "team": "Arsenal", "era": "1980s"},
    {"name": "Javier Zanetti", "position": "ST", "speed": 91, "dribbling": 79, "shooting": 85, "defense": 54, "physical": 84, "iq": 90, "team": "Inter Milan", "era": "1930s"},
    {"name": "Peixoto", "position": "LW", "speed": 87, "dribbling": 75, "shooting": 84, "defense": 33, "physical": 94, "iq": 78, "team": "AC Milan", "era": "1930s"},
    {"name": "Luke Shaw", "position": "LW", "speed": 88, "dribbling": 84, "shooting": 86, "defense": 28, "physical": 80, "iq": 81, "team": "Liverpool", "era": "1990s"},
    {"name": "Ghiggia Alcides", "position": "ST", "speed": 82, "dribbling": 90, "shooting": 85, "defense": 47, "physical": 81, "iq": 85, "team": "Real Madrid", "era": "1990s"},
    {"name": "Ubaldo Fillol", "position": "LW", "speed": 82, "dribbling": 77, "shooting": 91, "defense": 49, "physical": 82, "iq": 78, "team": "Juventus", "era": "2010s"},
    {"name": "Hajto", "position": "LW", "speed": 96, "dribbling": 83, "shooting": 82, "defense": 59, "physical": 80, "iq": 78, "team": "Manchester United", "era": "2020s"},
    {"name": "Jung Jo-gook", "position": "ST", "speed": 86, "dribbling": 77, "shooting": 91, "defense": 56, "physical": 77, "iq": 84, "team": "Arsenal", "era": "2000s"},
    {"name": "Makoto Hasebe", "position": "LW", "speed": 84, "dribbling": 75, "shooting": 83, "defense": 37, "physical": 97, "iq": 83, "team": "Inter Milan", "era": "1980s"},
    {"name": "Victor Osimhen", "position": "ST", "speed": 87, "dribbling": 77, "shooting": 84, "defense": 30, "physical": 89, "iq": 78, "team": "Inter Milan", "era": "1930s"},
    {"name": "Bruno Fernandes", "position": "ST", "speed": 95, "dribbling": 75, "shooting": 88, "defense": 40, "physical": 75, "iq": 82, "team": "Real Madrid", "era": "2020s"},
    {"name": "Oblitas Daniel", "position": "ST", "speed": 84, "dribbling": 94, "shooting": 84, "defense": 49, "physical": 75, "iq": 96, "team": "Paris SG", "era": "1980s"},
    {"name": "Lucas Paquetá", "position": "LW", "speed": 88, "dribbling": 82, "shooting": 83, "defense": 40, "physical": 85, "iq": 87, "team": "Barcelona", "era": "1970s"},
    {"name": "Lúcio", "position": "ST", "speed": 92, "dribbling": 86, "shooting": 82, "defense": 33, "physical": 78, "iq": 96, "team": "Arsenal", "era": "1970s"},
    {"name": "George Weah", "position": "ST", "speed": 84, "dribbling": 80, "shooting": 88, "defense": 35, "physical": 80, "iq": 81, "team": "Napoli", "era": "1990s"},
    {"name": "Yerry Mina", "position": "LW", "speed": 95, "dribbling": 81, "shooting": 84, "defense": 58, "physical": 76, "iq": 96, "team": "AC Milan", "era": "1970s"},
    {"name": "Davinson Sánchez", "position": "LW", "speed": 89, "dribbling": 85, "shooting": 83, "defense": 38, "physical": 78, "iq": 81, "team": "Napoli", "era": "1990s"},
    {"name": "Stefan Medina", "position": "LW", "speed": 85, "dribbling": 92, "shooting": 83, "defense": 53, "physical": 75, "iq": 85, "team": "Bayern Munich", "era": "2020s"},
    {"name": "Pedro Rodríguez", "position": "ST", "speed": 91, "dribbling": 79, "shooting": 83, "defense": 31, "physical": 81, "iq": 81, "team": "Napoli", "era": "2010s"},
    {"name": "Eric Cantona", "position": "ST", "speed": 83, "dribbling": 75, "shooting": 82, "defense": 54, "physical": 94, "iq": 92, "team": "Napoli", "era": "2010s"},
    {"name": "Fabián Soria", "position": "LW", "speed": 89, "dribbling": 76, "shooting": 87, "defense": 60, "physical": 77, "iq": 81, "team": "Arsenal", "era": "1990s"},
    {"name": "Benjamin Moukandou", "position": "ST", "speed": 89, "dribbling": 84, "shooting": 82, "defense": 39, "physical": 77, "iq": 81, "team": "Manchester United", "era": "2000s"},
    {"name": "Balotelli", "position": "LW", "speed": 85, "dribbling": 81, "shooting": 85, "defense": 30, "physical": 78, "iq": 85, "team": "Paris SG", "era": "1950s"},
    {"name": "Tyrone Mings", "position": "ST", "speed": 86, "dribbling": 78, "shooting": 85, "defense": 45, "physical": 78, "iq": 79, "team": "Arsenal", "era": "1970s"},
    {"name": "Thomas Müller", "position": "ST", "speed": 82, "dribbling": 81, "shooting": 87, "defense": 38, "physical": 75, "iq": 88, "team": "Juventus", "era": "1970s"},
    {"name": "Marco van Basten", "position": "ST", "speed": 85, "dribbling": 77, "shooting": 87, "defense": 30, "physical": 75, "iq": 93, "team": "Paris SG", "era": "2000s"},
    {"name": "Filippo Inzaghi", "position": "LW", "speed": 85, "dribbling": 78, "shooting": 83, "defense": 42, "physical": 80, "iq": 96, "team": "Barcelona", "era": "1950s"},
    {"name": "Krol Wim", "position": "ST", "speed": 84, "dribbling": 79, "shooting": 82, "defense": 47, "physical": 78, "iq": 81, "team": "Chelsea", "era": "1990s"},
    {"name": "Coloccini", "position": "ST", "speed": 84, "dribbling": 75, "shooting": 84, "defense": 29, "physical": 75, "iq": 82, "team": "Inter Milan", "era": "2010s"},
]

def get_forwards():
    """Return all forwards"""
    return FORWARDS
