"""Hermaniland - Porteros (Goalkeepers) Database"""

GOALKEEPERS = [
    {"name": "Seo Jung-jin", "position": "GK", "speed": 78, "dribbling": 32, "shooting": 24, "defense": 97, "physical": 98, "iq": 96, "team": "AC Milan", "era": "2020s"},
    {"name": "Vagner", "position": "GK", "speed": 82, "dribbling": 43, "shooting": 20, "defense": 99, "physical": 95, "iq": 95, "team": "Barcelona", "era": "1930s"},
    {"name": "Rio Ferdinand", "position": "GK", "speed": 75, "dribbling": 41, "shooting": 22, "defense": 98, "physical": 97, "iq": 93, "team": "Manchester United", "era": "2020s"},
    {"name": "Bengt Nyberg", "position": "GK", "speed": 79, "dribbling": 49, "shooting": 45, "defense": 95, "physical": 98, "iq": 95, "team": "Napoli", "era": "1950s"},
    {"name": "Jairzinho", "position": "GK", "speed": 77, "dribbling": 34, "shooting": 37, "defense": 98, "physical": 92, "iq": 98, "team": "Chelsea", "era": "2020s"},
    {"name": "Gigio Donnarumma", "position": "GK", "speed": 75, "dribbling": 53, "shooting": 29, "defense": 99, "physical": 94, "iq": 91, "team": "AC Milan", "era": "2010s"},
    {"name": "Cazorla", "position": "GK", "speed": 82, "dribbling": 48, "shooting": 44, "defense": 96, "physical": 98, "iq": 87, "team": "Arsenal", "era": "1930s"},
    {"name": "Alfredo Di Stéfano", "position": "GK", "speed": 78, "dribbling": 46, "shooting": 26, "defense": 93, "physical": 98, "iq": 92, "team": "Paris SG", "era": "2000s"},
    {"name": "Ansu Fati", "position": "GK", "speed": 77, "dribbling": 35, "shooting": 22, "defense": 94, "physical": 93, "iq": 96, "team": "Inter Milan", "era": "1950s"},
    {"name": "Aleksandr Smertin", "position": "GK", "speed": 71, "dribbling": 33, "shooting": 38, "defense": 94, "physical": 92, "iq": 97, "team": "Napoli", "era": "2020s"},
    {"name": "Giorgio Chiellini", "position": "GK", "speed": 75, "dribbling": 33, "shooting": 26, "defense": 99, "physical": 87, "iq": 97, "team": "Liverpool", "era": "1950s"},
    {"name": "Robbie Fowler", "position": "GK", "speed": 72, "dribbling": 30, "shooting": 30, "defense": 94, "physical": 92, "iq": 96, "team": "Liverpool", "era": "2020s"},
    {"name": "Bosnich", "position": "GK", "speed": 80, "dribbling": 52, "shooting": 31, "defense": 98, "physical": 87, "iq": 98, "team": "Napoli", "era": "2010s"},
    {"name": "Martín Montoya", "position": "GK", "speed": 72, "dribbling": 54, "shooting": 42, "defense": 97, "physical": 97, "iq": 78, "team": "Manchester United", "era": "1970s"},
    {"name": "Jørn Andersen", "position": "GK", "speed": 81, "dribbling": 33, "shooting": 44, "defense": 93, "physical": 91, "iq": 98, "team": "Liverpool", "era": "1980s"},
    {"name": "Leandro Paredes", "position": "GK", "speed": 71, "dribbling": 53, "shooting": 24, "defense": 95, "physical": 92, "iq": 91, "team": "Real Madrid", "era": "1990s"},
    {"name": "Kaka", "position": "GK", "speed": 81, "dribbling": 30, "shooting": 42, "defense": 97, "physical": 94, "iq": 83, "team": "Bayern Munich", "era": "1970s"},
    {"name": "Vanenburg", "position": "GK", "speed": 72, "dribbling": 41, "shooting": 36, "defense": 95, "physical": 89, "iq": 97, "team": "Juventus", "era": "2000s"},
    {"name": "Larsson", "position": "GK", "speed": 73, "dribbling": 44, "shooting": 21, "defense": 96, "physical": 89, "iq": 94, "team": "Juventus", "era": "1990s"},
    {"name": "Carvalho", "position": "GK", "speed": 70, "dribbling": 39, "shooting": 24, "defense": 90, "physical": 92, "iq": 98, "team": "Juventus", "era": "1980s"},
    {"name": "Insigne", "position": "GK", "speed": 82, "dribbling": 35, "shooting": 40, "defense": 92, "physical": 96, "iq": 85, "team": "Bayern Munich", "era": "1990s"},
    {"name": "Cristiano Ronaldo", "position": "GK", "speed": 74, "dribbling": 37, "shooting": 34, "defense": 93, "physical": 92, "iq": 90, "team": "Liverpool", "era": "1980s"},
    {"name": "Alan Shearer", "position": "GK", "speed": 71, "dribbling": 33, "shooting": 21, "defense": 91, "physical": 91, "iq": 91, "team": "Juventus", "era": "1990s"},
    {"name": "Paul Scholes", "position": "GK", "speed": 70, "dribbling": 34, "shooting": 26, "defense": 97, "physical": 89, "iq": 81, "team": "Liverpool", "era": "2020s"},
    {"name": "Gonzalo Jara", "position": "GK", "speed": 79, "dribbling": 39, "shooting": 37, "defense": 97, "physical": 90, "iq": 78, "team": "Arsenal", "era": "1990s"},
    {"name": "Hirving Lozano", "position": "GK", "speed": 76, "dribbling": 30, "shooting": 27, "defense": 89, "physical": 91, "iq": 91, "team": "Inter Milan", "era": "1980s"},
    {"name": "Braathen", "position": "GK", "speed": 80, "dribbling": 46, "shooting": 44, "defense": 91, "physical": 88, "iq": 90, "team": "Paris SG", "era": "2020s"},
    {"name": "Giovani Lo Celso", "position": "GK", "speed": 81, "dribbling": 35, "shooting": 33, "defense": 99, "physical": 84, "iq": 82, "team": "Manchester United", "era": "1950s"},
    {"name": "Diogo Leite", "position": "GK", "speed": 82, "dribbling": 51, "shooting": 25, "defense": 89, "physical": 86, "iq": 98, "team": "Barcelona", "era": "1970s"},
    {"name": "Jürgen Damm", "position": "GK", "speed": 77, "dribbling": 39, "shooting": 20, "defense": 99, "physical": 78, "iq": 92, "team": "Real Madrid", "era": "1980s"},
    {"name": "Son Heung-min", "position": "GK", "speed": 80, "dribbling": 53, "shooting": 22, "defense": 95, "physical": 84, "iq": 87, "team": "Liverpool", "era": "1930s"},
    {"name": "Nemanja Vidic", "position": "GK", "speed": 70, "dribbling": 48, "shooting": 23, "defense": 91, "physical": 91, "iq": 79, "team": "Juventus", "era": "2020s"},
    {"name": "Sandro Mazzola", "position": "GK", "speed": 80, "dribbling": 50, "shooting": 32, "defense": 89, "physical": 87, "iq": 90, "team": "Barcelona", "era": "1930s"},
    {"name": "José Fonte", "position": "GK", "speed": 79, "dribbling": 38, "shooting": 45, "defense": 95, "physical": 83, "iq": 84, "team": "Bayern Munich", "era": "2000s"},
    {"name": "Jorge Campos", "position": "GK", "speed": 78, "dribbling": 32, "shooting": 39, "defense": 90, "physical": 90, "iq": 79, "team": "Real Madrid", "era": "1990s"},
    {"name": "Oribe Peralta", "position": "GK", "speed": 79, "dribbling": 35, "shooting": 30, "defense": 88, "physical": 85, "iq": 93, "team": "Real Madrid", "era": "1950s"},
    {"name": "Willy Sagnol", "position": "GK", "speed": 72, "dribbling": 36, "shooting": 25, "defense": 94, "physical": 84, "iq": 78, "team": "Manchester United", "era": "1930s"},
    {"name": "Zizinho", "position": "GK", "speed": 74, "dribbling": 45, "shooting": 30, "defense": 99, "physical": 77, "iq": 80, "team": "Bayern Munich", "era": "1930s"},
    {"name": "Michael Ballack", "position": "GK", "speed": 72, "dribbling": 44, "shooting": 30, "defense": 97, "physical": 78, "iq": 81, "team": "Barcelona", "era": "1930s"},
    {"name": "Edenilson", "position": "GK", "speed": 74, "dribbling": 54, "shooting": 22, "defense": 90, "physical": 83, "iq": 84, "team": "Paris SG", "era": "1970s"},
    {"name": "Reece James", "position": "GK", "speed": 75, "dribbling": 38, "shooting": 38, "defense": 95, "physical": 76, "iq": 87, "team": "Liverpool", "era": "1980s"},
]

def get_goalkeepers():
    """Return all goalkeepers"""
    return GOALKEEPERS
